DEFRA/waste-exemptions-engine

.travis.yml
README.md
spec/dummy/config/database.travis.yml

For all our ruby projects we integrate the GitHub project with
- Travis-CI
- Codeclimate (maintainability)
- Codeclimate (test coverage)
These changes cover what is needed to do this from the code perspective.

Integrate the project with our standard CI tools

---

app/controllers/waste_exemptions_engine/contact_position_forms_controller.rb
app/forms/waste_exemptions_engine/contact_position_form.rb
app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
app/validators/waste_exemptions_engine/position_validator.rb
app/views/waste_exemptions_engine/contact_position_forms/new.html.erb
config/locales/forms/contact_position_forms/en.yml
config/routes.rb
db/migrate/20181217223323_add_contact_position_to_enrollments.rb

This change follows the existing pattern for adding pages, though there is a slight change in its validator. Position is an optional field in the waste exemptions service and as such we have added a new position validator that permits a blank field.
If its not blank then we validate its not too long and doesn't contain any characters we would not expect in a position.

Add contact position field

---

app/controllers/waste_exemptions_engine/is_a_farm_forms_controller.rb
app/forms/waste_exemptions_engine/is_a_farm_form.rb
app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
app/validators/waste_exemptions_engine/yes_no_validator.rb
app/views/waste_exemptions_engine/is_a_farm_forms/new.html.erb
config/locales/forms/is_a_farm_forms/en.yml
config/routes.rb
db/migrate/20181217234231_add_is_a_farm_to_enrollments.rb

This deviates slightly from the pattern set down in Waste Carriers Renewals in that rather than holding a string value for the answer (either "yes" or "no") we are able to do what we should of done which is hold the result as a boolean. The field permits null and this represents an unanswered result.
Other than that it implements the WCR pattern for a Yes/No page.

Add is a farm page

---

Gemfile.lock
app/controllers/waste_exemptions_engine/operator_postcode_forms_controller.rb
app/controllers/waste_exemptions_engine/postcode_forms_controller.rb
app/forms/waste_exemptions_engine/operator_postcode_form.rb
app/forms/waste_exemptions_engine/postcode_form.rb
app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
app/models/waste_exemptions_engine/enrollment.rb
app/models/waste_exemptions_engine/interim.rb
app/services/waste_exemptions_engine/address_finder_service.rb
app/validators/waste_exemptions_engine/postcode_validator.rb
app/views/waste_exemptions_engine/operator_postcode_forms/new.html.erb
app/views/waste_exemptions_engine/shared/_os_terms_footer.html.erb
config/locales/en.yml
config/locales/forms/operator_postcode_forms/en.yml
config/routes.rb
db/migrate/20181218182531_create_interims.rb
waste_exemptions_engine.gemspec

This is the first page in the process of adding an address for the operator, but also setups up a few other things to support this.
**New interim object**
The old version of the WEX service essentially returned you to the same page, though now with a populated lookup list of addresses found. This meant it didn't need to retain the postcode within the db as part of the round trip. However it also meant a very complex implementation, and not our best user experience.
WCR where we are copying the code from has the latest version of looking up an address, which splits the postcode lookup, result selection and manual address entry into completely separate pages. However it relies on there being a temporary postcode field on the underlying object. This is fine in WCR because when a transient …

Adds the operator post code page

---

app/controllers/waste_exemptions_engine/address_forms_controller.rb
app/controllers/waste_exemptions_engine/operator_address_forms_controller.rb
app/forms/waste_exemptions_engine/address_form.rb
app/forms/waste_exemptions_engine/operator_address_form.rb
app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
app/models/waste_exemptions_engine/address.rb
app/models/waste_exemptions_engine/enrollment.rb
app/services/waste_exemptions_engine/address_finder_service.rb
app/validators/waste_exemptions_engine/address_validator.rb
app/views/waste_exemptions_engine/operator_address_forms/new.html.erb
app/views/waste_exemptions_engine/shared/_select_address.html.erb
config/locales/forms/operator_address_forms/en.yml
config/routes.rb
db/migrate/20181219171050_create_addresses.rb

Following on from adding the first postcode lookup page, we can now add the address selection page.
Again we have taken the WCR code as a basis, however we have had to make a number of changes. First, the results we get back are in a slightly different format because we are using the addressbase facade in WEX. Secondly we are dealing with active record associations.
We have also needed to add another model for holding the address, and linked it to enrollment via a has_many association.
Other than that though, the implementation follows a standard model controller, form objects, validation and locales.

Add operator address lookup selection page

---

app/controllers/waste_exemptions_engine/operator_address_manual_forms_controller.rb
app/forms/waste_exemptions_engine/manual_address_form.rb
app/forms/waste_exemptions_engine/operator_address_manual_form.rb
app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
app/models/waste_exemptions_engine/address.rb
app/services/waste_exemptions_engine/address_finder_service.rb
app/views/waste_exemptions_engine/operator_address_manual_forms/new.html.erb
app/views/waste_exemptions_engine/shared/_manual_address.html.erb
config/locales/en.yml
config/locales/forms/operator_address_manual_forms/en.yml
config/routes.rb
db/migrate/20181221144235_add_mode_to_addresses.rb

With the operator postcode and address lookup pages sorted, the next step was to bring in the manual address entry page. Like the previous changes this brings in the base classes and additional migrations to support this work, so when we come to add these address pages for other areas the change will be much smaller.
We've also had to make some alterations based on the fact that we are working with a PostgresSql backed model, the most impacted being mass attribute assignment. Rails has built in protections to prevent you from mass assignining attributes based on params the user has entered, so we have had to incorporate this within the changes made.

Add operator manual address entry page

---

app/controllers/waste_exemptions_engine/contact_postcode_forms_controller.rb
app/forms/waste_exemptions_engine/contact_postcode_form.rb
app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
app/views/waste_exemptions_engine/contact_postcode_forms/new.html.erb
config/locales/forms/contact_postcode_forms/en.yml
config/routes.rb
db/migrate/20181227104112_add_contact_postcode_to_interims.rb

Using the pattern we copied from Waste Carriers for looking up the operator address using a postcode, we've used it again the contact address.
The one difference here is that content does not change based on business type, so we have been able to delete those elements from the code for the contact postcode page.

Add contact postcode lookup page

---

app/forms/waste_exemptions_engine/contact_postcode_form.rb
app/forms/waste_exemptions_engine/operator_postcode_form.rb
app/forms/waste_exemptions_engine/postcode_form.rb
app/views/waste_exemptions_engine/contact_postcode_forms/new.html.erb
app/views/waste_exemptions_engine/operator_postcode_forms/new.html.erb
config/locales/forms/contact_postcode_forms/en.yml
config/locales/forms/operator_postcode_forms/en.yml

Having implemented another postcode page for the contact, we identified there was some duplication we could remove by pushing logic into the base PostcodeForm that both the contact and operator form objects inherited.

Refactor postcode form objects

---

app/controllers/waste_exemptions_engine/contact_address_lookup_forms_controller.rb
app/forms/waste_exemptions_engine/contact_address_form.rb
app/forms/waste_exemptions_engine/contact_address_lookup_form.rb
app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
app/models/waste_exemptions_engine/address.rb
app/models/waste_exemptions_engine/enrollment.rb
app/views/waste_exemptions_engine/contact_address_lookup_forms/new.html.erb
config/locales/forms/contact_address_lookup_forms/en.yml
config/locales/forms/contact_postcode_forms/en.yml
config/routes.rb

Using the pattern set out for the operator postcode page, this adds the page to handle selecting the contact address.

Add contact address lookup page

---

Gemfile.lock
app/controllers/waste_exemptions_engine/site_grid_reference_forms_controller.rb
app/forms/waste_exemptions_engine/site_grid_reference_form.rb
app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
app/models/waste_exemptions_engine/address.rb
app/models/waste_exemptions_engine/enrollment.rb
app/validators/waste_exemptions_engine/grid_reference_validator.rb
app/validators/waste_exemptions_engine/site_description_validator.rb
app/views/waste_exemptions_engine/site_grid_reference_forms/new.html.erb
config/locales/forms/site_grid_reference_forms/en.yml
config/routes.rb
db/migrate/20181228105322_add_grid_reference_to_addresses.rb
db/migrate/20181228105748_add_grid_reference_to_interims.rb
db/migrate/20181228113158_add_description_to_addresses.rb
db/migrate/20181228113251_add_site_description_to_interims.rb
waste_exemptions_engine.gemspec

This adds the site grid reference page to waste exemptions. This does not have an equivalent in Waste Carriers so we have taken the technical design from the waste exemptions model, but the UI design and content from Flood Risk Activity Exemptions (FRAE), which came after WEX and iterated it's site grid reference page.
This also brings in the [os_map_ref](https://github.com/DEFRA/os-map-ref) gem. Similar functionality was built into WEX, but then moved to this gem for FRAE. We use it to convert a National Grid Reference to an x & y (easting & northing) so we can then query the area lookup WFS service to determine the EA area. It also helps us validate that a grid reference is valid.

Add site grid reference page

---

db/migrate/20181231093833_change_description_to_be_text_in_addresses.rb
db/migrate/20181231093858_change_site_description_to_be_text_in_interims.rb

The next change we were about to work on was selecting the exemptions. One of the things we need prior to that is to import and store the exemptions to choose, and as we began work we were reminded there is a 'text' type in PostgreSql (we need to hold a description for the exemptions).
We then had a "doh!" moment when we realised that this would be a better way to hold the site description, as its more expressive of the type of information be held (multiple lines of text rather than a single text value) and gives us more flexitibility in the future.

Change site description columns to be text

---

app/controllers/waste_exemptions_engine/check_your_answers_forms_controller.rb
app/forms/waste_exemptions_engine/check_your_answers_form.rb
app/helpers/waste_exemptions_engine/application_helper.rb
app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
app/validators/waste_exemptions_engine/address_validator.rb
app/views/waste_exemptions_engine/check_your_answers_forms/new.html.erb
config/locales/forms/check_your_answers_forms/en.yml
config/routes.rb

The design and method for displaying previously entered answers is lifted straight from Waste Carriers. However as the content is different it has been heavily edited to match the Waste Exemptions journey.
There has been one slight tweak to the design as well. When it comes to referencing the locale content, rather than generic subheadings and fields from different sections aligned together, it has been broken down into sections.
This should hopefully make aligning the content and layout a little easier when changes are made in the future.

Add check your answers page

---

.travis.yml
app/controllers/waste_exemptions_engine/site_grid_reference_forms_controller.rb
app/controllers/waste_exemptions_engine/site_postcode_forms_controller.rb
app/forms/waste_exemptions_engine/site_postcode_form.rb
app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
app/views/waste_exemptions_engine/site_grid_reference_forms/new.html.erb
app/views/waste_exemptions_engine/site_postcode_forms/new.html.erb
config/locales/forms/site_postcode_forms/en.yml
config/routes.rb
db/migrate/20190103103408_add_site_postcode_to_interims.rb

This is following our pattern for postcode search pages in the app, with one slight tweak.
Moving from the site grid reference to the site postcode is an optional step, and not as a result of an error. Also it does not infer we want to enter the address manually.
Hence we have added a `skip_to_address` method to the controller, and event in the workflow to better reflect this.

Add site postcode page

---

app/forms/waste_exemptions_engine/address_manual_form.rb
app/forms/waste_exemptions_engine/postcode_form.rb
app/models/concerns/waste_exemptions_engine/can_strip_whitespace.rb

Some recent changes were made to the Waste Carriers project to sections of the code where we manipulate strings, mainly parameters to strip white space post submission.
These changes update the WEX project to match to try and keep the projects consistent.
For reference
- https://github.com/DEFRA/waste-carriers-renewals/pull/345
- https://github.com/DEFRA/waste-carriers-renewals/pull/347
- https://github.com/DEFRA/waste-carriers-renewals/pull/348

Update string handling to match WCR

---

app/controllers/waste_exemptions_engine/site_address_lookup_forms_controller.rb
app/forms/waste_exemptions_engine/site_address_form.rb
app/forms/waste_exemptions_engine/site_address_lookup_form.rb
app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
app/views/waste_exemptions_engine/site_address_lookup_forms/new.html.erb
config/locales/forms/site_address_lookup_forms/en.yml
config/routes.rb

This adds the page to select the site address based on results of a postcode lookup. It's essentially a duplicate of what we have already done for the operator and contact address.
To that end, we have also been a bit cheeky and added the code in `CanChangeWorkflowStatus` (though commented it out) to handle manual address entry, as it was easier to work out the transitions based on where we want to get to, rather than via an interim step.
They will be uncommented in a subsquent commit.

Add site address lookup page

---

app/controllers/waste_exemptions_engine/site_address_manual_forms_controller.rb
app/forms/waste_exemptions_engine/site_address_manual_form.rb
app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
app/models/waste_exemptions_engine/address.rb
app/views/waste_exemptions_engine/site_address_manual_forms/new.html.erb
config/locales/forms/site_address_manual_forms/en.yml
config/routes.rb

Follows the pattern set for manual address entry, and copies what we have done for the operator and contact.
In addition it includes a new feature specific to the site address, where we use the OS Places postcode lookup to determine the x & y (easting and northing) for a manually entered an address.
Bringing in the current design for address entry (originated in FRAE) makes it less likely that a user can get an unknown postcode in. With this additional change we can move a step closer to 100% of addresses having an X & Y, and therefore our ability to determine the EA Admin area they belong to.

Add site manual address entry page

---

app/controllers/waste_exemptions_engine/declaration_forms_controller.rb
app/forms/waste_exemptions_engine/check_your_answers_form.rb
app/forms/waste_exemptions_engine/declaration_form.rb
app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
app/views/waste_exemptions_engine/declaration_forms/new.html.erb
config/locales/forms/declaration_forms/en.yml
config/routes.rb
db/migrate/20190104133305_add_declaration_to_enrollments.rb

Using the WCR declaration as a model, we implement it here but update the content to match WEX's declaration page.
We also fix an issue found with the check details page, caused by the fact that `is_a_farm` and `on_a_farm` are stored as boolean's, though when we validate them in their own forms the params are passed as strings (hence the confusion around what validation to use).

Add declaration page

---

app/controllers/waste_exemptions_engine/registration_complete_forms_controller.rb
app/forms/waste_exemptions_engine/registration_complete_form.rb
app/models/concerns/waste_exemptions_engine/can_change_exemption_status.rb
app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
app/models/waste_exemptions_engine/enrollment.rb
app/models/waste_exemptions_engine/enrollment_exemption.rb
app/views/waste_exemptions_engine/registration_complete_forms/new.html.erb
config/locales/forms/registration_complete_forms/en.yml
config/routes.rb
db/migrate/20190104151459_add_reference_to_enrollments.rb
db/migrate/20190104153628_add_date_fields_to_enrollment_exemptions.rb
db/migrate/20190104154234_add_status_to_enrollment_exemptions.rb

Taking the logic of Waste Carriers we have updated the content to match the waste exemptions registration complete page.
Part of the changes require us for the first time to mark state of the exemption (active, ceased, revoked, expired etc) plus the dates it was registered and will expire. We also need to handle generating the reference number for the enrollment.
As with Waste Carriers, wherever we have to record and transition state in an entity we use a state machine. Hence the introduction of `can_change_exemption_status` in this change.

Add registration complete page

---

config/locales/forms/applicant_email_forms/en.yml
config/locales/forms/applicant_name_forms/en.yml
config/locales/forms/applicant_phone_forms/en.yml
config/locales/forms/business_type_forms/en.yml
config/locales/forms/check_your_answers_forms/en.yml
config/locales/forms/contact_address_lookup_forms/en.yml
config/locales/forms/contact_address_manual_forms/en.yml
config/locales/forms/contact_email_forms/en.yml
config/locales/forms/contact_name_forms/en.yml
config/locales/forms/contact_phone_forms/en.yml
config/locales/forms/contact_position_forms/en.yml
config/locales/forms/declaration_forms/en.yml
config/locales/forms/is_a_farm_forms/en.yml
config/locales/forms/on_a_farm_forms/en.yml
config/locales/forms/operator_address_lookup_forms/en.yml
config/locales/forms/operator_address_manual_forms/en.yml
config/locales/forms/operator_name_forms/en.yml
config/locales/forms/registration_complete_forms/en.yml
config/locales/forms/registration_number_forms/en.yml
config/locales/forms/site_address_lookup_forms/en.yml
config/locales/forms/site_address_manual_forms/en.yml

This change does 2 things
- it corrects the copy for the operator name to ensure we are asking for the registered or official name and never a trading name
- it makes the heading when a validation error(s) occur consistent across all pages.

Fix copy for org. name and validtion header

---

app/views/waste_exemptions_engine/check_your_answers_forms/new.html.erb

Spotted that we were not populating the company registration number on the content of the check details page.

Fix broken company reg. no. in check your answers

---

app/mailers/waste_exemptions_engine/confirmation_mailer.rb
app/models/concerns/waste_exemptions_engine/can_change_exemption_status.rb
app/presenters/waste_exemptions_engine/certificate_presenter.rb
app/services/waste_exemptions_engine/address_finder_service.rb
app/services/waste_exemptions_engine/companies_house_service.rb
app/views/pages/version.html.erb
app/views/waste_exemptions_engine/confirmation_mailer/send_confirmation_email.html.erb
config/initializers/wickedpdf.rb
lib/waste_exemptions_engine.rb

Prior to this change configuration was essentially reading env vars directly, or assuming that the host application had set something in its application.rb and made it available via `Rails.configuration`.
As we started to look at adding our missing tests, we realised that we'd have to adopt this same pattern in our dummy app if we wanted this to work.
Ideally we want never to have to touch the code generated for the dummy app, hence we went looking for an alternative.
https://guides.rubyonrails.org/engines.html#configuring-an-engine details how to go about providing configuration for an engine, and this not only solved the test problem but also felt like a better approach.
Hence these changes implement the mechanism to allow a host application to pass in config values, and updates the …

Implement configuration in the engine

---

app/views/waste_exemptions_engine/pdfs/certificate.html.erb
config/locales/pdfs/certificate.en.yml

Prior to this change the expires on date for each exemption was displayed in the formatt YYYY-MM-DD. To be consistent with other dates in the certificate we wanted to change this to be 'January 22 2019'.
The longer format would have forced each exemption to cover 2 lines, so we also tweeked the formatting of the exemption details section and how the date is shown in each row.

Improve exemptions dates in PDF certificate

---

app/views/waste_exemptions_engine/declaration_forms/new.html.erb

We were having trouble aligning the icon to some text in the declaration page, when it was highlighted that we don't use any icons in the Waste carriers renewals declaration page.
Therefore to keep the services consistent this change removes the image (and therefore the problem) from the declaration page.

Remove notice icon from declaration page

---

app/forms/waste_exemptions_engine/check_your_answers_form.rb
app/presenters/waste_exemptions_engine/certificate_presenter.rb

Because of the way we had the validation configured previously it was only letting us enter a site location using grid reference and description.
This change adds a conditional to the validation i.e. if the site was set using a grid reference use one set of validation, else use the other.

Fix site validation in check answers page

---

app/mailers/waste_exemptions_engine/confirmation_mailer.rb
app/models/concerns/waste_exemptions_engine/can_change_exemption_status.rb
app/presenters/waste_exemptions_engine/certificate_presenter.rb
app/services/waste_exemptions_engine/address_finder_service.rb
app/services/waste_exemptions_engine/companies_house_service.rb
app/views/pages/version.html.erb
app/views/waste_exemptions_engine/confirmation_mailer/send_confirmation_email.html.erb
config/initializers/wickedpdf.rb
lib/waste_exemptions_engine.rb

We have a known issue with the regex in the companies house validation and as we copied this from Waste Carriers it means the same issue is there. Rather than simply updating both, we are building a shared gem for validation that can then be used by both services.
As part of building the [Defra Ruby Validators gem](https://github.com/DEFRA/defra-ruby-validators) we needed to provide it with the companies house API key.
We didn't want to just rely on having the gem read env vars directly so we followed a common pattern of the host app using a configuration block to set the gem's configuration
```ruby
DefraRubyValidators.configure do |configuration|
configuration.companies_house_api_key = ENV["COMPANIES_HOUSE_API_KEY"]
end
```
Prior to this change the engine followed a slightly different …

Convert to block style configuration

---

app/views/pages/version.html.erb

This was moved to the configuration block in https://github.com/DEFRA/waste-exemptions-engine/pull/48.
---
Spotted when running tests on the back-office.

Fix location of git_repository_url on version page

---

spec/support/database_cleaner.rb

When working on PR #53 found we found we were struggling to get the tests to run without PG errors about violation of unique keys popping up.
Some digging found the database was not actually being cleaned before the tests started. A review of [DatabaseCleaner's guidance](https://github.com/DatabaseCleaner/database_cleaner#rspec-example) suggested a different config setup to what we have, and implementing it resolved all our issues with the test.
Hence this change to fix the config.

Fix database cleaner config

---

app/forms/waste_exemptions_engine/registration_number_form.rb
spec/factories/forms/registration_number_form.rb
spec/factories/transient_registration.rb
spec/forms/waste_exemptions_engine/registration_number_form_spec.rb

It was spotted during the testing of the new service that if you entered a registration number using lowercase characters, or added any whitespace then the check against companies house would fail.
The registration form should handle this on behalf of users rather than returning an error and expecting them to correct it. The changes included here will resolve both problems.

Fix issues with company no. validation

---

spec/rails_helper.rb
spec/spec_helper.rb
spec/support/simplecov.rb

We always drop simplecov into our projects to give us our test coverage. We did this as usual in this project and were a little surprised to see very high test coverage even though we know we are very few tests 😳.
As we have started adding tests the total coverage has started to fluctuate quite drastically so we took a deeper look at our test coverage.
What we found is that
- our dummy app's code files were being included, and reported as having 100% test coverage which inflated our overall figure
- simplecov was only reporting test coverage for files 'touched' by the existing unit tests
Clearly this is wrong and not giving us the accurate figure we need to make a proper assessment about our unit test coverage.
Therefore this change is intended to fix the issue. It follows our adopted …

Fix our simplecov configuration

---

app/controllers/waste_exemptions_engine/forms_controller.rb
spec/controllers/waste_exemptions_engine/forms_controller_spec.rb

https://eaflood.atlassian.net/browse/RUBY-23
It was noted in testing that if you hit refresh on the last page of the journey you would get an error.
The problem is that between the declaration page being submitted and the end (completion) page being shown the transient registration has passed through the `RegistrationCompletionService`. This converts the transient registration to a registration, and deletes the transient.
So if a user hits refresh they are essentially requesting they wish to see a transient registration that no longer exists.
In consultation with our QA and the Product Manager we have agreed that if a user makes a request for a transient registration that does not exist (the **token** is not recognised) they will be redirected to the root page of the service.
This change …

Handle refresh on the completion page

---

spec/rails_helper.rb

When aligning the engine's rspec setup with the back-office-ta project spotted that we had the line
```ruby
config.use_transactional_fixtures = false
```
in `rails_helper.rb`. We didn't have this in the back-office-ta project, and as we are using Databasecleaner it doesn't make sense to also have this line confusing issues. Hence this change removes it.

Remove rspec use transaction fixtures config

---

spec/rails_helper.rb

Admittedly we don't have any request specs at this stage, but in preparation and to align this engine with the test setup for the Waste Carriers engine, this change ensures url helpers are included before running any request specs.

Include url helpers in request specs

---

app/controllers/waste_exemptions_engine/application_controller.rb

Improved testing during DEFRA/waste-exemptions-back-office-ta#21 revealed that the mounted engine wasn't using any of the auth checks provided by Devise in the host app - an unauthenticated user couldn't access routes from the host app, but could access ones in the mounted engine.
This also applied to checks for abilities as well.
The front-office doesn't use Devise or CanCanCan to manage authorisation or authentication, but the engine should be able to handle it when the host app specifies it.

Inherit authorisation/authentication preferences from host

---

app/forms/waste_exemptions_engine/postcode_form.rb
app/validators/concerns/waste_exemptions_engine/can_validate_presence.rb
app/validators/concerns/waste_exemptions_engine/validates_presence.rb
app/validators/waste_exemptions_engine/address_validator.rb
app/validators/waste_exemptions_engine/base_validator.rb
app/validators/waste_exemptions_engine/postcode_validator.rb
lib/waste_exemptions_engine/engine.rb
spec/cassettes/postcode_no_matches.yml
spec/cassettes/postcode_valid.yml
spec/dummy/config/application.rb
spec/dummy/config/initializers/waste_exemptions_engine.rb
spec/dummy/config/locales/postcode_validator/en.yml
spec/dummy/db/schema.rb
spec/factories/forms/contact_postcodes_form.rb
spec/factories/forms/operator_postcodes_form.rb
spec/factories/forms/site_postcodes_form.rb
spec/forms/waste_exemptions_engine/contact_postcode_form_spec.rb
spec/forms/waste_exemptions_engine/exemptions_form_spec.rb
spec/forms/waste_exemptions_engine/operator_postcode_form.rb
spec/forms/waste_exemptions_engine/registration_number_form_spec.rb
spec/forms/waste_exemptions_engine/site_postcode_form.rb
spec/support/helpers/error_translator.rb
spec/support/shared_examples/forms/postcode_form.rb
spec/support/shared_examples/forms/validated_form.rb
spec/support/shared_examples/validators/presence_validator.rb
spec/support/shared_examples/validators/validator.rb
spec/support/vcr.rb
spec/validators/waste_exemptions_engine/address_validator_spec.rb
spec/validators/waste_exemptions_engine/postcode_validator_spec.rb

In an effort to remove duplication in the validators, we would like to move duplicated code into the ValidatesPresence concern and BaseValidator class. 
Future refactoring efforts will include the creation of the ValidatesLength concern.
This PR is a sample of the intended refactoring. We decided it would be easier to review the changes if they are applied to a single validator before applying the pattern to the rest of the validators.

Refactor AddressValidator

---

app/views/waste_exemptions_engine/applicant_name_forms/new.html.erb
app/views/waste_exemptions_engine/applicant_phone_forms/new.html.erb
app/views/waste_exemptions_engine/contact_name_forms/new.html.erb
app/views/waste_exemptions_engine/contact_phone_forms/new.html.erb
app/views/waste_exemptions_engine/contact_postcode_forms/new.html.erb
app/views/waste_exemptions_engine/operator_postcode_forms/new.html.erb
app/views/waste_exemptions_engine/site_grid_reference_forms/new.html.erb
app/views/waste_exemptions_engine/site_postcode_forms/new.html.erb

https://eaflood.atlassian.net/browse/RUBY-96
* This will replace existing form input width styling with that of the gov design system, making approximation where required (i.e. we can't import the actual styles yet, but replication should make a clean upgrade path).
This need to be reviewed in tandem with https://github.com/DEFRA/waste-exemptions-front-office/pull/23
Merge this before the front-office PR to prevent layout regression.

Form widths classes added to relevant views

---

spec/validators/waste_exemptions_engine/postcode_validator_spec.rb

We regularly need to update our VCR cassettes to prevent errors during build. Recreating them essentially means running the test suite every couple of weeks.
We could speed up this process however by specifying which specs we want to run. In this case we only care about those specs that use VCR, hence adding a tag to them would help speed up the process.
To then only run those specs tagged as using vcr you would use
```bash
bundle exec rspec -t vcr
```

Tag rspecs that use VCR

---

app/forms/waste_exemptions_engine/address_form.rb
app/forms/waste_exemptions_engine/address_lookup_form.rb
config/locales/forms/contact_address_lookup_forms/en.yml
config/locales/forms/operator_address_lookup_forms/en.yml
config/locales/forms/site_address_lookup_forms/en.yml

https://eaflood.atlassian.net/browse/RUBY-83
While testing RUBY-83, Tim found an unhandled 500 error when submitting the address form. This PR attempts to fix that error.
WIPThe includes includes an adjustment of the validation in the AddressLookupForm class to ensure the messaging and behaviour is consistent with WCR.

Fix address form 500 error

---

app/views/waste_exemptions_engine/shared/_select_address.html.erb

https://eaflood.atlassian.net/browse/RUBY-83
Tim found that the link in the address form error isn't properly linking to the form element. This PR fixes that.

Fix address form error link

---

config/locales/partials/person_name.en.yml

This should fix the `translation missing: en.waste_exemptions_engine.shared.person_name.first_name` error encountered in the back office.

Add missing label text for person name form partial

---

spec/forms/waste_exemptions_engine/exemptions_form_spec.rb

While working on the model tests, I noticed that the ExemptionsForm spec was dependent on the order the tests were executed. The spec fails when any test Exemptions are created prior to the execution of the ExemptionsForm spec. Randomly choosing three Exemptions from the test DB instead of hard coding the submitted IDs solves this problem.

Fix order dependence in ExemptionsForm spec

---

spec/forms/waste_exemptions_engine/exemptions_form_spec.rb

This fixes an intermittent failure in the ExemptionsForm spec. The spec was expecting to compare sorted arrays of exemption codes. Since the code is a combination of "U" and an integer, the sorting was insufficient when the integer was greater than 9 since string sorting will sort "U10" before "U9". Using `match_array` fixes this as the order is not relevant.

Fix the intermittent failure of the ExemptionsForm spec

---

config/locales/forms/check_your_answers_forms/en.yml

This should be `contact details` and not `contact deatils`.

Fix typo on check details page

---

app/controllers/waste_exemptions_engine/forms_controller.rb

PR #88 introduced the idea of successful and unsuccessful redirect codes. The intent is to help us distinguish between redirects where everything is fine e.g. transitions in the journey, and redirects as a result of an invalid transition.
We added these as constants to the application controller so that everything which inherits `WasteExemptionsEngine::ApplicationController` could make use of them.
In our tests, and when running our host apps locally using webrick everything seems fine. However when deployed in `production` we get this error
```
I, [2019-03-13T11:00:09.085543 #6919]  INFO -- : Completed 500 Internal Server Error in 73ms (ActiveRecord: 14.4ms)
F, [2019-03-13T11:00:09.089913 #6919] FATAL -- :
NameError (uninitialized constant …
```

Use explicit reference to redirect constants

---

Gemfile.lock
waste_exemptions_engine.gemspec

Previously our Gemfiles locked Rails to a specific version (4.2.11). This meant that Dependabot would not prompt us with upgrades. As there is now a critical security patch we'd like to apply, we've decided it's better to accept 4.2.11 and above (within the 4.2 range). This should allow Dependabot to submit PRs for patch-level changes to Rails.

Unlock Rails version

---

lib/waste_exemptions_engine/engine.rb

This came out of our story to implement PaperTrail in this engine and the back office. Since we were tracking models in both projects, we ended up with two migrations to create a Versions table, which then caused a clash. So rather than have two migrations, it makes sense for the engine's migrations to take precidence, and for it to handle the creation of the versions table.

Load engine migrations before host app migrations

---

app/services/waste_exemptions_engine/registration_completion_service.rb
db/migrate/20190314161232_add_assistance_mode_to_registrations.rb
lib/waste_exemptions_engine.rb
spec/dummy/db/schema.rb
spec/services/waste_exemptions_engine/registration_completion_service_spec.rb

https://eaflood.atlassian.net/browse/RUBY-200
A registration should have a different assistance_mode depending on whether it was submitted through the front-office or back-office. This allows us to track what proportion of registrations are assisted digital.

Save the assistance mode for a registration

---

db/migrate/20190319133740_add_deregistration_message_to_registration_exemption.rb
spec/cassettes/company_no_valid.yml
spec/dummy/db/schema.rb
spec/models/waste_exemptions_engine/transient_registration_exemption_spec.rb
spec/support/helpers/model_properties.rb

The "deregister individual exemptions" feature in the WEX back-office needs a new column on the `registration_exemptions` table. The `deregistration_message` column is used to store the reason why an exemption is being deregistered.

Add message column to registration exemption

---

db/migrate/20190326133420_add_deregistered_on_to_registration_exemption.rb
spec/cassettes/postcode_no_matches.yml
spec/cassettes/postcode_valid.yml
spec/dummy/db/schema.rb
spec/support/helpers/model_properties.rb

The exemption de-registration functionality needs to record the DateTime when the de-registration occurs. This PR adds the date column necessary to record this data.
This is a dependency for the completion of DEFRA/waste-exemptions-back-office-ta/pull/90/.

 Add deregistered_on to registration_exemptions

---

config/initializers/wickedpdf.rb
lib/waste_exemptions_engine.rb

We noticed that the one boolean config values is being used as a string in the code requiring the `value =="true"` pattern.
This PR refactors this so the config value can be set as a string but referenced as a boolean in the code.

Refactor boolean config values to behave as booleans

---

app/controllers/waste_exemptions_engine/last_email_controller.rb
app/services/waste_exemptions_engine/last_email_cache_service.rb
config/routes.rb
lib/waste_exemptions_engine.rb
spec/dummy/.env.example
spec/dummy/config/initializers/waste_exemptions_engine.rb
spec/requests/waste_exemptions_engine/last_email_spec.rb
spec/services/waste_exemptions_engine/last_email_cache_service_spec.rb

In order to improve the flow of the end-to-end tests, we want to add behaviour to the application that will support the storage of the last email that was sent. There will also be a route that returns the latest mail object as JSON. The feature will be enabled through the use of an ENV var so we can ensure the endpoint is only accessible when the feature is explicitly enabled.

Add email interception and retrieval

---

config/initializers/time_formats.rb

Spotted that we were using `%e` for our default date formats, which actaully returns a blank-padded day of the month (eg ` 1` with a space in front of it) instead of the unpadded value we want (eg `1`). This update fixes the format.

Format dates with unpadded day instead of blank-padded

---

spec/services/waste_exemptions_engine/generate_pdf_service_spec.rb

Actually created this as part of [PR 117](https://github.com/DEFRA/waste-exemptions-engine/pull/117) but there is a good chance that is going to be closed without merging.
However there is no sense in chucking away the work of creating the tests hence this standalone change to add the missing tests for the service.

Add missing tests for GeneratePdfService

---

app/views/waste_exemptions_engine/pdfs/privacy_policy.html

https://eaflood.atlassian.net/browse/RUBY-216
Data protection asked us to include a copy of the privacy policy for those users who complete their registration via NCCC as assisted digital.
The team looked at the problem and decided it would just be simpler and meet the need more if we just attached a copy of the policy to all emails.
However as the policy contains no dynamic elements there would be no need to generate it each time we send the email. It would be better if we could generate the PDF ahead of time, add it as a static asset to the projects and then just attach that asset to the confirmation email.
The need to generate and update the PDF will be very infrequent (we are talking years) so rather than try and do anything ourselves we will just take advantage of available online …

Add html view which is used to generate PDF privacy

---

app/services/waste_exemptions_engine/confirmation_pdf_generator_service.rb

This solves a bug on the most recent refactoring for which the `render_to_string` method fails outside of a request scope because the included application Layout depends on the presence of a `@_request` object. Since we don't need our PDF's views to be rendered with a layout, this PR explicitly tells rails not to fetch it.

Add `layout: false` when rendering PDF views to string.

---

spec/models/waste_exemptions_engine/transient_registration_workflow_state/contact_address_lookup_form_spec.rb
spec/models/waste_exemptions_engine/transient_registration_workflow_state/contact_postcode_form_spec.rb
spec/models/waste_exemptions_engine/transient_registration_workflow_state/operator_address_lookup_form_spec.rb
spec/models/waste_exemptions_engine/transient_registration_workflow_state/operator_postcode_form_spec.rb
spec/models/waste_exemptions_engine/transient_registration_workflow_state/site_address_lookup_form_spec.rb
spec/models/waste_exemptions_engine/transient_registration_workflow_state/site_postcode_form_spec.rb
spec/support/shared_examples/models/transient_registration_workflow_state/a_postcode_transition.rb
spec/support/shared_examples/models/transient_registration_workflow_state/an_address_lookup_transition.rb

https://eaflood.atlassian.net/browse/RUBY-62
This PR adds some shared examples for the address workflow tests.
This will reduce duplication now, and prevent even more of it when we add more workflow tests for the edit workflow.

Refactor address workflow tests to use shared examples

---

app/services/waste_exemptions_engine/registration_completion_service.rb
spec/requests/waste_exemptions_engine/registration_complete_forms_spec.rb

https://eaflood.atlassian.net/browse/RUBY-221
Raise error to the end user when it is resqued from the completition service.

Raise completition errors to the customer

---

config/routes.rb

Part of: https://eaflood.atlassian.net/browse/RUBY-261
The dummy app inside the engine correctly handles 404 and 500 errors but the applications
that inherit from the engine always render a general template for every error. 
This is because the wrong path is sent together as an ":id" and hence the information about the error template to use is lost in time and space. 
Changing the URL constraint fixed this issue.

Fix error routes to contain a constraint for the /error path

---

Gemfile.lock
spec/spec_helper.rb
waste_exemptions_engine.gemspec

byebug has a very similar interface as gdb, but byebug does not use the powerful Pry REPL.
binding.pry uses Pry, but lacks some of the byebug features.
[pry-byebug](https://github.com/deivid-rodriguez/pry-byebug) brings some capabilities byebug to binding.pry, so using that, will give you the most debugging powers.
Credits: https://docs.gitlab.com/ee/development/pry_debugging.html#byebug-vs-bindingpry

Remove byebug and swap it with pry-byebug

---

app/helpers/waste_exemptions_engine/edit_helper.rb
app/views/waste_exemptions_engine/edit_forms/new.html.erb
config/initializers/time_formats.rb
config/locales/forms/edit_forms/en.yml
spec/helpers/waste_exemptions_engine/edit_helper_spec.rb

https://eaflood.atlassian.net/browse/RUBY-62
This PR displays some metadata about when the EditRegistration was created and updated. This is to reduce the risk of a user coming to an already-in-progress edit and not realising that previous changes have been made.

Display metadata about EditRegistration

---

spec/models/waste_exemptions_engine/new_registration_workflow_state/location_form_spec.rb

During a code review on a different PR (https://github.com/DEFRA/waste-exemptions-engine/pull/139#discussion_r279319422) we decided we'd strip these out as the test on the transition itself was enough.

Remove expectations for private methods from location specs

---

app/assets/stylesheets/waste_exemptions_engine/partials/_edit.scss
app/views/waste_exemptions_engine/edit_forms/new.html.erb
config/locales/forms/edit_forms/en.yml

https://eaflood.atlassian.net/browse/RUBY-62
This PR makes some styling and text changes to make the edit page a little more human-friendly. This includes:
- aligning the tables
- translating raw DB values into more human-readable text where necessary

Fix up styling on edit page

---

spec/requests/waste_exemptions_engine/last_email_spec.rb

These tests were being skipped until the error handling bug was fixed: https://github.com/DEFRA/waste-exemptions-engine/pull/145
However, when the skip was removed, it turned out that trying to access these routes when the config disabled them actually resulted in a RoutingError, not a 404. I believe this is because of how the route's constraints are set up.

Don't skip last email request tests

---

app/services/waste_exemptions_engine/edit_completion_service.rb
spec/services/waste_exemptions_engine/edit_completion_service_spec.rb

https://eaflood.atlassian.net/browse/RUBY-62
When a registration is edited, if it keeps the same exemptions, the status of those exemptions should not change.
This fixes a bug which always reset the status to active.

Don't modify status of unedited exemptions

---

app/controllers/concerns/waste_exemptions_engine/edit_permission_checks.rb
app/services/waste_exemptions_engine/edit_permission_checker_service.rb

Part of https://eaflood.atlassian.net/browse/RUBY-330
This moves the permissions checkers in its own service to allow easier re-define of class on the engine apps

Move edit authorization checking to its own service

---

app/models/waste_exemptions_engine/transient_registration_exemption.rb
spec/support/shared_examples/models/activator_of_exemptions.rb

While working on some bugs I have found out that the authomatically defined scopes for states coming from AASM on the TransientRegistrationExemptions were generating wrong query due to the fact that the authomatically generated AASM model scopes for states were using the wrong table name. Added regression tests.
Before:
```
[3] pry(#<#<Class:0x00007f8f245ada38>>)> @edit_form.registration_exemptions.active.to_sql
=> "SELECT \"transient_registration_exemptions\".* FROM \"transient_registration_exemptions\" WHERE \"transient_registration_exemptions\".\"transient_registration_id\" = 10 AND \"waste_exemptions_engine_transient_registration_exemptions\".\"state\" = 'active'"
```
After:
```
[1] pry(#<#<Class:0x00007f91bb42b388>>)> @edit_form.registration_exemptions.active.to_sql
=> "SELECT …
```

Set table name before including state machine concern

---

app/models/waste_exemptions_engine/edit_registration.rb
app/models/waste_exemptions_engine/registration.rb
app/models/waste_exemptions_engine/registration_exemption.rb
spec/factories/registration.rb
spec/models/waste_exemptions_engine/registration_spec.rb

https://eaflood.atlassian.net/browse/RUBY-62 this addresses point 1 of the QA document
This define a new association in the Registration model so that we can get an handy list of only active registration. I have defined the scope manually on the `RegistrationExemption` class rather then include the `CanActivateExemption` concern, since we don't really want that class to be able to deal with changing the status of an exemption (yet).
Thought it might make sense to externalise the list of statuses (for validations purposes and the ability to have the status AASM scopes defined in the model) and leave only the transaction code in the `CanActivateExemption`.
In the meantime this does the job :D

Copy over to transient Edit registration only active exemptions

---

app/assets/stylesheets/waste_exemptions_engine/partials/_edit.scss
app/views/waste_exemptions_engine/edit_forms/new.html.erb

Addresses point 6 of QA document from https://eaflood.atlassian.net/browse/RUBY-62
It was necessary to add missing classes in order to make this work as intended. BEM style has been used. It was not possible to achieve this by using the grid system for alignment issues and this simple solution looked better than hacking into the styles classes.
<details> <summary>Responsiveness</summary>
</details>

Add cannot edit to the exemptions section in edit screen

---

app/models/concerns/waste_exemptions_engine/can_be_located_by_grid_reference.rb
app/models/waste_exemptions_engine/address.rb
app/models/waste_exemptions_engine/transient_address.rb
app/views/waste_exemptions_engine/edit_forms/new.html.erb
config/locales/forms/edit_forms/en.yml

Addresses point 10 of QA document from https://eaflood.atlassian.net/browse/RUBY-62
In order to address some consistency issues with the way we display site addresses,
this change introduces an if statement to deal with different heading and table rows whether an address is located by grid reference or is inserted manually.
<details>
<summary> Site address </summary>
</details>
<details>
<summary> Manual address </summary>
</details>
Mind that the 2 `Change` links in the grid reference section redirect to the same location. I have tried a `rowspan=2` but it looked really horrible. We might want to consider to put the link at the caption level as done for the `no edit` in https://github.com/DEFRA/waste-exemptions-engine/pull/173 but this is more a question for designers. This result IMO is …

Change headings and table layout on edit site location

---

app/views/waste_exemptions_engine/main_people_forms/new.html.erb

https://eaflood.atlassian.net/browse/RUBY-347
This PR fixes a few failures in the conditional logic used to display HTML.
It fixes the number of `div` closing tags that are used, so they should now all be closed properly, preventing the footer from running into the `main` tag in IE11.
It also makes sure that only one `ul` tag is used for the list of added people, rather than one `ul` tag per person.

Fix conditionals on main people page

---

app/presenters/waste_exemptions_engine/certificate_presenter.rb
spec/presenters/waste_exemptions_engine/certificate_presenter_spec.rb

Spotted in a the `CertificatePresenter` that we had a `partnership?`method  however we already have that built into the registration via the `CanHaveRegistrationAttributes`.
As the `CertificatePresenter` delegates any calls it does not recognise down to the registration instance, deleting the method will have no impact on anything that uses the presenter.

Remove duplicate partnership? method

---

app/views/waste_exemptions_engine/site_grid_reference_forms/new.html.erb
config/locales/forms/site_grid_reference_forms/en.yml

https://eaflood.atlassian.net/browse/RUBY-341
Add a message regarding the possibility for the user to insert an address manually at the top of the page, just below the heading. This is because it has been reported that the user doesn't notice the link at the bottom of the page and is a temporary solution until we make include a switch form
<details>
<summary>Screenshot</summary>
</details>

Move up reference link to manual address for site form

---

app/assets/stylesheets/waste_exemptions_engine/partials/_edit.scss
app/views/waste_exemptions_engine/edit_forms/new.html.erb

https://eaflood.atlassian.net/browse/RUBY-367
This fixes once and for all the position of the `cannot edit` label to be the far right of the caption heading. A `small` tag has been used as it is one of the few W3C allowed tags to nest, however, classes have been used to achieve a reduced font size and the floating right behaviour.
<details>
<summary>View</summary>
</details>

Fix `cannot edit` label in caption to float right inline with title

---

db/migrate/20190522085202_rename_deregistered_on_to_deregistered_at.rb
spec/dummy/db/schema.rb
spec/support/helpers/model_properties.rb

This is just about keeping things consistent. Where we are recording a timestamp the pattern has been to use `name_of_field_at` rather than `name_of_field_on`.
For example `created_at`, `updated_at`, and `submitted_at`. This change is just about keeping things consistent.

Rename deregistered_on to deregistered_at

---

Gemfile.lock
app/forms/waste_exemptions_engine/check_your_answers_form.rb
app/forms/waste_exemptions_engine/registration_number_form.rb
lib/waste_exemptions_engine.rb
spec/forms/waste_exemptions_engine/check_your_answers_form_spec.rb
spec/forms/waste_exemptions_engine/registration_number_form_spec.rb

[defra-ruby-validators](https://github.com/DEFRA/defra-ruby-validators) updated its namespace to fall inline with our new agreed convention of using `DefraRuby::MyNamespace`, as set out in [defra-ruby-exporters](https://github.com/DEFRA/defra-ruby-exporters).
This obviously means the engine has to update it's references to it hence these changes.

Update to work with validators namespace change

---

app/controllers/waste_exemptions_engine/forms_controller.rb
app/forms/waste_exemptions_engine/edit_form.rb

https://eaflood.atlassian.net/browse/RUBY-352
The registration was saved at every refresh because of the workflow setup.
Since the object is persisted already at every `submit`, I have added a guard clause to avoid updating it unless it is persisted. 
BUT the editing journey is instead expecting a persisted object since the first call. Hence a fix there was necessary too.  
I wasn't able to find a nice way to test it :/ we should run some tests in truncation mode or do some weird stubbing and expectations.

Do not save un-persisted objects in workflow setup

---

app/views/waste_exemptions_engine/site_grid_reference_forms/new.html.erb

https://eaflood.atlassian.net/browse/RUBY-370
Given the new design message, we now want to get rid of the second link to manual address form on the bottom of the page.
<details> <summary>Screenshot</summary> 
</details>

Remove second link to manual address

---

spec/dummy/config/environments/test.rb

Translation errors should be caught during unit tests so none of them make it through our CI.

Raise I18n errors during tests

---

app/services/waste_exemptions_engine/base_service.rb

Since not all services always needs params, let's make sure we can run services without params. 
Bug came out while I was working on: https://github.com/DEFRA/waste-exemptions-back-office-ta/pull/191/files

Allow a service main method to receive no params

---

db/migrate/20190603152123_add_area_to_addresses.rb
db/migrate/20190603215354_add_area_to_transient_addresses.rb
spec/dummy/db/schema.rb
spec/support/helpers/model_properties.rb

https://eaflood.atlassian.net/browse/RUBY-25
The existing service has the ability to lookup the EA admin area for a site using the easting and northing values. This is currently out of action whilst we await a fix (the external service we call changed supplier and we have been awaiting support for what the new query should be).
However it has been spotted in our work on migrating the old data to the new schema that we don't have a field for this. So on the basis we want to retain this data, and that we expect to implement the lookup feature in the new service once the issue is resolved, this change adds a migration to add the required field.

Add area attribute to addresses

---

app/models/concerns/waste_exemptions_engine/can_have_registration_attributes.rb
app/models/concerns/waste_exemptions_engine/can_limit_number_of_main_people.rb
app/validators/waste_exemptions_engine/business_type_validator.rb
app/views/waste_exemptions_engine/business_type_forms/new.html.erb
spec/factories/new_registration.rb
spec/factories/registration.rb
spec/forms/waste_exemptions_engine/business_type_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/business_type_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/operator_name_form_spec.rb
spec/support/shared_examples/models/owner_of_registration_attributes.rb
spec/validators/waste_exemptions_engine/business_type_validator_spec.rb

Resolves https://github.com/DEFRA/ruby-services-team/issues/17
This commit creates a new HashWithIndifferentAccess for storing the string values for business types. It also starts using that hash in the checks in the module.

Create a hash for business types

---

spec/cassettes/company_no_valid.yml
spec/cassettes/postcode_no_matches.yml
spec/cassettes/postcode_valid.yml
spec/support/shared_examples/forms/address_lookup_form.rb

When updating our VCR cassettes, we noticed that the data we get back from OS Places for our test postcode has changed. This meant that the address tests could fail if a no-longer-valid UPRN was used.
This commit fixes the test and refreshes the cassettes.

Update address lookup test, reload cassettes

---

db/migrate/20190625221942_create_version_archives.rb
spec/dummy/db/schema.rb

https://eaflood.atlassian.net/browse/RUBY-25
As part of the first release of this version of the service we will be migrating data from the existing version into our new schema.
The migration will include audit history stored in the existing data. We already have a migration in place and tested for the user records. As the structure of the user records has changed very little this has not been an issue, and how [papertrail](https://github.com/paper-trail-gem/paper_trail) is working for the User model is sufficient.
However when it comes to the registrations, the structure has changed considerably. Plus we reviewed how auditing is currently working in this version of the service to help inform the migration work. What we found is that
- when we create a registration we get 4 entries; 1 …

Add versions archive table migration

---

app/views/waste_exemptions_engine/shared/_select_address.html.erb

While working on setting up spec tests for the errors we show to the user, we found that the address lookup pages were the only pages not showing the message in line with the field.
Seems like some of the code necessary for the field to show was there but pointing to `addresses` rather than `temp_addresses`. I decided to just adapt the code to work in both cases when there are errors on `addresses` and when there are in `temp_addresses`.
Test coverage will come in a separate PR.

Show error messages in line with address select fields

---

app/views/waste_exemptions_engine/declaration_forms/new.html.erb
spec/requests/waste_exemptions_engine/declaration_forms_spec.rb

While working to add test coverage on our error messages in request specs we have noticed that the declaration page does not show the error message in line with the checkbox. After talking to our design expert we decided that should be added.

Show second error message on declaration page

---

app/models/waste_exemptions_engine/new_registration.rb
app/models/waste_exemptions_engine/registration.rb
app/services/waste_exemptions_engine/registration_completion_service.rb
spec/services/waste_exemptions_engine/registration_completion_service_spec.rb

In order to avoid skipping registration numbers and to keep them sequential, we want to move the creation of the reference in the Registration object creation rather than the Transient registration. 
By doing this before going live there is no downtime involved in the change.

Create reference using the registration id 

---

app/controllers/waste_exemptions_engine/registration_complete_forms_controller.rb
app/services/waste_exemptions_engine/registration_completion_service.rb

Since forms are created using transient_registrations, we have the need to copy over the reference from the created registration in the confirmation form page.

Fixes registration number appearing after the declaration page

---

.travis.yml
app/services/waste_exemptions_engine/registration_completion_service.rb
spec/services/waste_exemptions_engine/registration_completion_service_spec.rb

From: https://eaflood.atlassian.net/browse/RUBY-523
In order to avoid race conditions creating broken registration records, this PR adds a test coverage which take advantage of Ruby Threads to recreate the race condition.
To fix the race condition, we have decided to use the `transient_registration` workflow_state to run an update on the object which will make it possible to take advantage of the https://api.rubyonrails.org/classes/ActiveRecord/Locking/Pessimistic.html.

Use DB Pessimistic locking to prevent race conditions

---

app/controllers/waste_exemptions_engine/renews_controller.rb
app/models/waste_exemptions_engine/renewing_registration.rb
app/services/waste_exemptions_engine/renewal_start_service.rb
app/views/waste_exemptions_engine/renews/new.html.erb
config/routes.rb
spec/factories/renewing_registration.rb
spec/models/waste_exemptions_engine/renewing_registration_spec.rb
spec/requests/waste_exemptions_engine/renew_spec.rb
spec/requests/waste_exemptions_engine/start_forms_spec.rb
spec/services/waste_exemptions_engine/renewal_start_service_spec.rb

https://eaflood.atlassian.net/browse/RUBY-491
When a user starts the WEX renewal process, we need to create a new database record to store their in-progress renewal.
As a start, we need to create a new RenewingRegistration subtype of TransientRegistration.

Create a new transient registration for WEX renewals

---

app/controllers/waste_exemptions_engine/renew_with_changes_forms_controller.rb
app/controllers/waste_exemptions_engine/renewal_complete_forms_controller.rb
app/controllers/waste_exemptions_engine/renewal_start_forms_controller.rb
app/forms/waste_exemptions_engine/renew_with_changes_form.rb
app/forms/waste_exemptions_engine/renewal_complete_form.rb
app/forms/waste_exemptions_engine/renewal_start_form.rb
app/models/concerns/waste_exemptions_engine/can_use_renewing_registration_workflow.rb
app/models/waste_exemptions_engine/renewing_registration.rb
app/views/waste_exemptions_engine/renew_with_changes_forms/new.html.erb
app/views/waste_exemptions_engine/renewal_complete_forms/new.html.erb
app/views/waste_exemptions_engine/renewal_start_forms/new.html.erb
app/views/waste_exemptions_engine/renews/new.html.erb
config/locales/forms/renew_with_changes_forms/en.yml
config/locales/forms/renewal_complete_forms/en.yml
config/locales/forms/renewal_start_forms/en.yml
config/routes.rb
spec/factories/forms/renewal_complete_form.rb
spec/factories/forms/renewal_start_form.rb
spec/factories/forms/renewal_with_changes_form.rb
spec/forms/waste_exemptions_engine/renewal_complete_form_spec.rb
spec/models/waste_exemptions_engine/renewing_registration_workflow_state/renew_with_changes_form_spec.rb
spec/models/waste_exemptions_engine/renewing_registration_workflow_state/renewal_complete_form_spec.rb
spec/models/waste_exemptions_engine/renewing_registration_workflow_state/renewal_start_form_spec.rb
spec/requests/waste_exemptions_engine/renew_with_changes_forms_spec.rb
spec/requests/waste_exemptions_engine/renewal_complete_forms_spec.rb
spec/requests/waste_exemptions_engine/renewal_start_forms_spec.rb

https://eaflood.atlassian.net/browse/RUBY-516
This story covers:
- creating a new state machine to handle the renewal workflow
- applying the renewal state machine to the renewals model
- creating skeleton versions of the ‘Do you want to renew with these details?', 'you are about to renew', and 'renewal complete’ pages - each page should just be a heading and a 'continue' button

Create new state machine for renewals

---

app/models/concerns/waste_exemptions_engine/can_use_new_registration_workflow.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/applicant_name_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/check_your_answers_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/exemptions_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/location_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/site_address_lookup_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/site_address_manual_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/site_grid_reference_form_spec.rb
spec/support/helpers/workflow_states.rb
spec/support/shared_examples/requests/get_form.rb
spec/support/shared_examples/requests/post_form.rb

From: https://eaflood.atlassian.net/browse/RUBY-457
Change the state machine and fix tests so that the exemptions screen will now appear just after the location screens.
Other fixes were necessary on the test suite for all this to run. First thing that went wrong with them, is that removing the exemptions form between the site address and check your answers screen was generating an issue with the helper we use to fetch the correct `previous state` of a form. The code that was there was doing very little on fetching the correct previous status, was not accounting for multiple options, like is the case when dealing with the site_address, and was using "next" AASM events rather than "back" ones, so it was actually working just by chances rather than correct logic.
Once that was fixed to …

Change position of the Exemptions form

---

app/controllers/waste_exemptions_engine/registration_complete_forms_controller.rb
app/controllers/waste_exemptions_engine/renewal_complete_forms_controller.rb
app/forms/waste_exemptions_engine/renewal_complete_form.rb
app/services/waste_exemptions_engine/registration_completion_service.rb
app/views/waste_exemptions_engine/renewal_complete_forms/new.html.erb
config/locales/forms/renewal_complete_forms/en.yml
spec/requests/waste_exemptions_engine/renewal_complete_forms_spec.rb
spec/services/waste_exemptions_engine/registration_completion_service_spec.rb

https://eaflood.atlassian.net/browse/RUBY-517
When a user reaches the "renewal complete" page, we should create a new registration with the data they just confirmed.
The renewing_registration record should also be deleted from the database.

Complete renewal and create new registration

---

app/forms/waste_exemptions_engine/renewal_start_form.rb
app/models/waste_exemptions_engine/transient_registration.rb
app/views/waste_exemptions_engine/renewal_start_forms/new.html.erb
config/locales/forms/renewal_start_forms/en.yml
db/migrate/20190801171410_add_temp_renew_without_changes_to_transient_registration.rb
spec/dummy/db/schema.rb
spec/forms/waste_exemptions_engine/renewal_start_form_spec.rb
spec/requests/waste_exemptions_engine/renewal_start_forms_spec.rb
spec/support/helpers/model_properties.rb

https://eaflood.atlassian.net/browse/RUBY-493
https://eaflood.atlassian.net/browse/RUBY-498
These buttons will be used to route the user to the declaration or through the longer journey through the forms.

Add options to renewal start page

---

app/helpers/waste_exemptions_engine/mailer_helper.rb

https://github.com/DEFRA/waste-exemptions-back-office-ta/pull/308
Whilst working on another task in another project we identified that the way we were generating the path in the mailer was invalid.
Where path is `"/app/assets/images/waste_exemptions_engine/logo_ea.png"` we expected `Rails.root.join(path)` to return something like `"/vagrant/waste-exemptions-back-office-ta/app/assets/images/logo_ea.png"`.
When we got in there with `binding.pry` though we found this
```bash
[1] pry(#<#<Class:0x000055c9347abc20>>)> path
=> "/app/assets/images/logo_ea_color.png"
[2] pry(#<#<Class:0x000055c9347abc20>>)> Rails.root.join(path)
=> #<Pathname:/app/assets/images/logo_ea_color.png>
[3] pry(#<#<Class:0x000055c9347abc20>>)> Rails.root
=> #<Pathname:/vagrant/waste-exemptions-back-office-ta>
[4] …
```

Apply path fix to mailer helper

---

app/controllers/waste_exemptions_engine/renew_without_changes_forms_controller.rb
app/forms/waste_exemptions_engine/renew_without_changes_form.rb
app/models/concerns/waste_exemptions_engine/can_use_renewing_registration_workflow.rb
app/views/waste_exemptions_engine/renew_without_changes_forms/new.html.erb
config/locales/forms/renew_without_changes_forms/en.yml
config/routes.rb
spec/cassettes/w3c_valid_content/renew_without_changes_forms_spec.yml
spec/factories/forms/renewal_without_changes_form.rb
spec/factories/renewing_registration.rb
spec/models/waste_exemptions_engine/renewing_registration_workflow_state/declaration_form_spec.rb
spec/models/waste_exemptions_engine/renewing_registration_workflow_state/renew_without_changes_form_spec.rb
spec/models/waste_exemptions_engine/renewing_registration_workflow_state/renewal_start_form_spec.rb
spec/requests/waste_exemptions_engine/renew_without_changes_forms_spec.rb

From: https://eaflood.atlassian.net/browse/RUBY-498
Add transition events and state to make it possible for the user to go on a different flow to the declaration page when choosing not to make changes to a renewal

Make it possible to jump directly into the declaration page at renewal

---

app/models/concerns/waste_exemptions_engine/can_copy_data_from_registration.rb
app/models/waste_exemptions_engine/registration.rb
app/models/waste_exemptions_engine/renewing_registration.rb
db/migrate/20190805152649_add_referring_registration_id_to_registrations.rb
spec/dummy/db/schema.rb
spec/factories/renewing_registration.rb
spec/models/waste_exemptions_engine/renewing_registration_spec.rb
spec/services/waste_exemptions_engine/registration_completion_service_spec.rb
spec/support/helpers/model_properties.rb
spec/support/shared_examples/models/transient_registration.rb

From: https://eaflood.atlassian.net/browse/RUBY-497
When creating a new registration from a renewal, we want to register what registration was renewed.

Record referring registration when renewing

---

app/models/concerns/waste_exemptions_engine/can_use_renewing_registration_workflow.rb
spec/factories/renewing_registration.rb
spec/models/waste_exemptions_engine/renewing_registration_workflow_state/is_a_farmer_form_spec.rb

From: https://eaflood.atlassian.net/browse/RUBY-502
Twick the renewals state machine and make sure to redirect the user to the correct site form (grid reference VS postal address) when renewing.

Redirect to correct site address form on Renewing

---

app/views/waste_exemptions_engine/shared/_errors.html.erb

https://eaflood.atlassian.net/browse/RUBY-468
We spotted a bug where clicking the validation error link redirected to a 404 instead of skipping down to the anchor tag, as intended.
This turned out to be down to Turbolinks being a little overzealous: https://github.com/turbolinks/turbolinks/issues/75
Adding `data-turbolinks="false"` fixes it.

Fix broken validation message links

---

app/models/waste_exemptions_engine/renewing_registration.rb
app/services/waste_exemptions_engine/registration_completion_service.rb

Two fixes were necessary:
The first is about adding a `&` on the Airbrake error reporting code for when an error is thrown before the `@registration` object is initialized.
The second fix is the actual problem. I was using the `token` from the Transient Registration to populate a referring registration, but that is incorrect as the 2 tokens are not going to match. What is going to match is instead the `reference`, and hence I have changed the code to use that in order to fetch the correct referring registration.

Fix bug on renewal creation

---

app/models/concerns/waste_exemptions_engine/can_use_renewing_registration_workflow.rb
spec/models/waste_exemptions_engine/renewing_registration_workflow_state/check_your_answers_form_spec.rb
spec/models/waste_exemptions_engine/renewing_registration_workflow_state/site_postcode_form_spec.rb

From: https://eaflood.atlassian.net/browse/RUBY-502
This adds back events checks on the site address workflow to redirect to the correct site address screen

Fix bug on site address workflow for renewal

---

app/models/waste_exemptions_engine/registration_exemption.rb
app/models/waste_exemptions_engine/transient_registration_exemption.rb

https://eaflood.atlassian.net/browse/RUBY-520
This change sorts the exemptions by the `exemption_id` value, so they should be listed in the order they appear on the form.

Add default ordering to registration exemptions

---

app/services/waste_exemptions_engine/registration_completion_service.rb
spec/factories/new_registration.rb
spec/services/waste_exemptions_engine/registration_completion_service_spec.rb

https://eaflood.atlassian.net/browse/RUBY-503
Some data is only required for registrations with certain business types - partnerships need partners, while limited companies and LLPs need Companies House numbers.
However, if the business type changes from one which requires this data to one which doesn't, we should remove the extra data.
This could be because the user changes the business type during renewal, but it could also happen during a new registration if they go through most of the process and then go back to change their business type.

Remove unnecessary data after business type change

---

app/models/waste_exemptions_engine/registration.rb
spec/dummy/db/schema.rb
spec/models/waste_exemptions_engine/registration_spec.rb

It was spotted in testing that we were only actually providing a grace period of 29 days. Hopefully the following scenario helps explain the situation.
- We have a registration that expires on 31 Jul 2019 (24:00)
- 31 Jul 2018 plus 30 days is Aug 30
- If the current time is 14:34 on Aug 30 `past_renewal_window?` would return true
- it should not return true until 00:00 on 31 Aug
The logic prior to this change was
```ruby
def past_renewal_window?
(expires_on + renewal_window_after_expiry_in_days.days) < Time.now
end
```
Initially we thought we could fix it by changing the comparison to `<=` however that still leads to the comparison returning `true`. The issue is actually the use of `Time` in a comparison that uses just date objects. Using this time and our example above you get `00:00 30 …

Fix past_renewal_window? to not drop one day

---

spec/factories/edit_registration.rb
spec/factories/forms/applicant_email_form.rb
spec/factories/forms/applicant_name_form.rb
spec/factories/forms/applicant_phone_form.rb
spec/factories/forms/business_type_form.rb
spec/factories/forms/contact_email_form.rb
spec/factories/forms/contact_name_form.rb
spec/factories/forms/contact_phone_form.rb
spec/factories/forms/contact_position_form.rb
spec/factories/forms/contact_postcodes_form.rb
spec/factories/forms/operator_name_form.rb
spec/factories/forms/operator_postcodes_form.rb
spec/factories/forms/site_grid_reference_form.rb
spec/factories/forms/site_postcodes_form.rb
spec/factories/renewing_registration.rb
spec/requests/waste_exemptions_engine/applicant_email_forms_spec.rb
spec/requests/waste_exemptions_engine/applicant_name_forms_spec.rb
spec/requests/waste_exemptions_engine/applicant_phone_forms_spec.rb
spec/requests/waste_exemptions_engine/contact_email_forms_spec.rb
spec/requests/waste_exemptions_engine/contact_name_forms_spec.rb
spec/requests/waste_exemptions_engine/contact_phone_forms_spec.rb
spec/requests/waste_exemptions_engine/contact_position_forms_spec.rb
spec/requests/waste_exemptions_engine/contact_postcode_forms_spec.rb
spec/requests/waste_exemptions_engine/operator_name_forms_spec.rb
spec/requests/waste_exemptions_engine/operator_postcode_forms_spec.rb
spec/requests/waste_exemptions_engine/site_grid_reference_forms_spec.rb
spec/requests/waste_exemptions_engine/site_postcode_forms_spec.rb

This adds request test coverage on relevant forms for edit and renew registration.
This will ensure we have at least one place that test the correct pre-fill of forms in those cases.

Add test coverage on edit and renewal transient registrations

---

app/forms/waste_exemptions_engine/address_lookup_form.rb
app/forms/waste_exemptions_engine/address_manual_form.rb
app/forms/waste_exemptions_engine/applicant_email_form.rb
app/forms/waste_exemptions_engine/applicant_name_form.rb
app/forms/waste_exemptions_engine/applicant_phone_form.rb
app/forms/waste_exemptions_engine/base_form.rb
app/forms/waste_exemptions_engine/business_type_form.rb
app/forms/waste_exemptions_engine/check_your_answers_form.rb
app/forms/waste_exemptions_engine/confirm_edit_cancelled_form.rb
app/forms/waste_exemptions_engine/contact_email_form.rb
app/forms/waste_exemptions_engine/contact_name_form.rb
app/forms/waste_exemptions_engine/contact_phone_form.rb
app/forms/waste_exemptions_engine/contact_position_form.rb
app/forms/waste_exemptions_engine/declaration_form.rb
app/forms/waste_exemptions_engine/edit_form.rb
app/forms/waste_exemptions_engine/exemptions_form.rb
app/forms/waste_exemptions_engine/is_a_farmer_form.rb
app/forms/waste_exemptions_engine/location_form.rb
app/forms/waste_exemptions_engine/on_a_farm_form.rb
app/forms/waste_exemptions_engine/operator_name_form.rb
app/forms/waste_exemptions_engine/person_form.rb
app/forms/waste_exemptions_engine/postcode_form.rb
app/forms/waste_exemptions_engine/registration_number_form.rb
app/forms/waste_exemptions_engine/renew_with_changes_form.rb
app/forms/waste_exemptions_engine/renew_without_changes_form.rb
app/forms/waste_exemptions_engine/renewal_start_form.rb
app/forms/waste_exemptions_engine/site_grid_reference_form.rb
app/forms/waste_exemptions_engine/start_form.rb

Since the advent of the edit functionality, we now se the form token in the `initialize` method, taking it from the transient_registration.
Hence, it is not any more needed for the `submit` to set the correct token.
Next step will be to make the `attributes` a method in the children classes that define which attributes from the form have to be updated in the transient registration.

Remove second token setting on forms

---

app/models/concerns/waste_exemptions_engine/can_copy_data_from_registration.rb
app/models/waste_exemptions_engine/registration.rb
app/models/waste_exemptions_engine/registration_exemption.rb
app/models/waste_exemptions_engine/renewing_registration.rb
spec/factories/registration.rb
spec/models/waste_exemptions_engine/edit_registration_spec.rb
spec/models/waste_exemptions_engine/registration_spec.rb
spec/models/waste_exemptions_engine/renewing_registration_spec.rb

https://eaflood.atlassian.net/browse/RUBY-594
When we start a renewal, if the registration has already expired and is in the grace period, we want to copy over the expired exemptions so they don't have to re-select them.
This will also mean the exemptions are listed in the magic link email if it is resent after expiry.

Copy expired registrations to RenewingRegistration

---

README.md

As we have a `Gemfile.lock` checked into source control, we can integrate with Hakiri!

Add hakiri security badge to README

---

app/controllers/waste_exemptions_engine/renews_controller.rb
app/models/waste_exemptions_engine/registration.rb
spec/models/waste_exemptions_engine/registration_spec.rb

Part of: https://eaflood.atlassian.net/browse/RUBY-602
Since we already check for the `already_renewed` concept in the engine, this refactor makes it a method that we can reuse on the backoffice for RUBY-602.

Add `already_renewed?` method to Registration

---

app/models/waste_exemptions_engine/registration.rb
app/models/waste_exemptions_engine/renewing_registration.rb
app/models/waste_exemptions_engine/transient_registration.rb
spec/models/waste_exemptions_engine/edit_registration_spec.rb
spec/models/waste_exemptions_engine/new_registration_spec.rb
spec/models/waste_exemptions_engine/registration_spec.rb
spec/models/waste_exemptions_engine/renewing_registration_spec.rb

Part of: https://eaflood.atlassian.net/browse/RUBY-506
This adds a common interface method on the registration classes.
A `Registration` is a `renewal` if it refers to another registration that exists.
A `TransientRegistration` is by default *not* a renewal, while a `RenewingRegistration` is by default a renwal.
This code is added to the engine in order to be reused in the backoffice (https://github.com/DEFRA/waste-exemptions-back-office-ta/pull/356)

Add `#renewal?` method to registration objects

---

app/forms/waste_exemptions_engine/applicant_name_form.rb
app/views/waste_exemptions_engine/applicant_name_forms/new.html.erb
config/locales/forms/applicant_name_forms/en.yml
spec/forms/waste_exemptions_engine/applicant_name_form_spec.rb
spec/requests/waste_exemptions_engine/applicant_name_forms_spec.rb

To facilitate the form refactoring and take advantage of delegate, we want to use transient registration attributes names were possible

Use applicant first and last name transient registration params

---

config/locales/forms/applicant_name_forms/en.yml

I have realised that the error message also rely on the attribute names, hence this is necessary to fix a missing translation error in the validation of the form

Rename translation errors parameters

---

app/forms/waste_exemptions_engine/contact_name_form.rb
app/views/waste_exemptions_engine/contact_name_forms/new.html.erb
config/locales/forms/contact_name_forms/en.yml
spec/forms/waste_exemptions_engine/contact_name_form_spec.rb
spec/requests/waste_exemptions_engine/contact_name_forms_spec.rb

In order to take advantage of a delegate approach, we want our attribute names to be consistent with what we define in the models.

Form refactoring - Rename contact first and last names

---

app/forms/waste_exemptions_engine/applicant_email_form.rb
spec/support/shared_examples/requests/post_form.rb

As part of the form refactoring, we want to be able to use delegate on our attributes and not re-write main initialize and submit methods.
In the case of the applicant confirmed email, we want the form to deal with the attribute in this different way, were we are able to set and read it and overwrite its value.
When sorting out the `submit` method, we will also change the setting of the attribute from params making use of callbacks with parameters.

Make confirmed email an attribute of the form

---

app/forms/waste_exemptions_engine/data_overview_form.rb
app/forms/waste_exemptions_engine/edit_form.rb
app/helpers/waste_exemptions_engine/application_helper.rb
app/views/waste_exemptions_engine/edit_forms/new.html.erb
app/views/waste_exemptions_engine/shared/data_overview/_applicant.html.erb
app/views/waste_exemptions_engine/shared/data_overview/_contact.html.erb
spec/dummy/app/helpers/application_helper.rb
spec/helpers/waste_exemptions_engine/application_helper_spec.rb

Instead of adding an attr_accessor to the form in order to format data for the view, we have decided to use Helpers.
This replace the form-defined methods with a `format_names` helper method used for applicant and contact names.

Forms refactoring - Use helpers to format names

---

app/forms/waste_exemptions_engine/exemptions_form.rb
app/helpers/waste_exemptions_engine/exemptions_forms_helper.rb
app/views/waste_exemptions_engine/exemptions_forms/new.html.erb
config/locales/forms/exemptions_forms/en.yml
spec/forms/waste_exemptions_engine/exemptions_form_spec.rb
spec/helpers/waste_exemptions_engine/exemptions_forms_helper_spec.rb
spec/requests/waste_exemptions_engine/exemptions_forms_spec.rb

Leave to the view what belongs to the view and to the form what belongs to the form :D
This change remove the list of exemptions being assigned to the form using the attribute name that is suppose to return the transient registration exemptions. It instead uses it as the real list of exemptions that are part of a registration or assign to them the registration ticked in the form itself. An helper is instead responsible to fetch the list of all exemptions for the view to show.

Forms refactoring - Exemptions form division of responsibilities

---

spec/helpers/waste_exemptions_engine/exemptions_forms_helper_spec.rb

I have observed that we randomly fail the scenario subject of this PR because the DB is in a dirty status.
Example: https://travis-ci.com/DEFRA/waste-exemptions-engine/builds/125219718

Prevent random failure of scenario

---

app/forms/waste_exemptions_engine/start_form.rb
app/views/waste_exemptions_engine/start_forms/new.html.erb
config/locales/forms/start_forms/en.yml
spec/forms/waste_exemptions_engine/start_form_spec.rb
spec/requests/waste_exemptions_engine/start_forms_spec.rb

As part of the form refactoring, this rename the form `start` attribute to `start_option`, in line with the transient_registration attribute name.

Rename start to start_option in the StartForm

---

app/forms/waste_exemptions_engine/postcode_form.rb
app/validators/waste_exemptions_engine/postcode_validator.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/site_grid_reference_form_spec.rb
spec/models/waste_exemptions_engine/renewing_registration_workflow_state/site_grid_reference_form_spec.rb
spec/support/shared_examples/models/transient_registration_workflow_state/a_postcode_transition.rb
spec/support/shared_examples/models/transient_registration_workflow_state/an_address_lookup_transition.rb

The `address_finder_error` attribute on the transient registration is used by the aasm machine to decide were to redirect the user.
Since the value has a default value of `false`, is only relevant to update it when we are updating the value to `true`.

Postcode form - Postcode validator

---

app/models/waste_exemptions_engine/transient_registration.rb
spec/factories/edit_registration.rb
spec/factories/new_registration.rb
spec/factories/renewing_registration.rb
spec/support/shared_examples/models/transient_registration.rb

With this little trick, we don't have to worry any more about stuff like "Can add or replace an address" as we have the ability to manipulate the transient addresses separate.
It does also make more sense logically and makes the form nested attribute implementation much easier.
The code using this is part of a bigger PR that will land later.

Add transient addresses has_one associations to TransientRegistration

---

app/models/concerns/waste_exemptions_engine/can_have_registration_attributes.rb
app/models/waste_exemptions_engine/registration.rb
app/models/waste_exemptions_engine/transient_registration.rb
spec/factories/edit_registration.rb
spec/models/waste_exemptions_engine/registration_spec.rb
spec/support/shared_examples/models/owner_of_registration_attributes.rb
spec/support/shared_examples/models/transient_registration.rb

In both the Registration and Transient registration we are implementing Rails association in order to associate those registration with the correct addresses.
We have decided that the name of the methods should be the same for bot Transient registration and non transient registration.
This allow for us to be able to easely reuse the same code on the 2 kind of object, and at the same time gives us the ability to edit and update the addresses on those registration without having to deal with the addresses array association complication.

Use rails associations to define associations with the addresses

---

app/assets/stylesheets/waste_exemptions_engine/application.scss
app/views/waste_exemptions_engine/exemptions_forms/new.html.erb
spec/cassettes/w3c_valid_content/exemptions_forms_spec/when-the-registration-is-in-the-correct-state.yml

From: https://eaflood.atlassian.net/browse/RUBY-608
We have tried to restyle the GDS elements checkbox to try achieve better reading for screen readers on our exemptions list.
In doing so, however, we have created a visual issue in the fact that the `focus` status's stile does not get applied to the checkboxes.
We have then decided to wait for GDS to deal with the screen readers issue (a ticket have been opened with them and is in their backlog).
So we are rolling back a part of this refactoring and the custom style in order to restore the checkboxes to their original behaviour.

Remove exemptions checkbox from inside label

---

app/models/waste_exemptions_engine/registration.rb
spec/factories/registration.rb
spec/models/waste_exemptions_engine/registration_spec.rb

In the back office, in more than one place, we have the need of get a unique list (scope) of active and expired exemptions since we want to be able to declare an order to the list.

Add active_and_expired_exemptions scope to registrations

---

app/views/waste_exemptions_engine/main_people_forms/new.html.erb

Closes: https://eaflood.atlassian.net/browse/RUBY-609
Add visually hidden text so that screen readers can distinguish a delete button from another in the main people list.

Add visually hidden name info to delete partner button

---

Gemfile.lock
app/models/waste_exemptions_engine/transient_address.rb
app/services/waste_exemptions_engine/area_lookup_service.rb
lib/waste_exemptions_engine/engine.rb
spec/cassettes/site_address_auto_x_and_y_and_area.yml
spec/cassettes/site_address_from_grid_ref_auto_area.yml
spec/cassettes/site_address_from_lookup_auto_area.yml
spec/models/waste_exemptions_engine/transient_address_spec.rb
spec/services/waste_exemptions_engine/area_lookup_service_spec.rb
waste_exemptions_engine.gemspec

https://eaflood.atlassian.net/browse/RUBY-483
The previous WEX service would attempt to identify the EA Admin area for a site once it had been entered as part of the registration. This stopped working in December 2018.
When we shipped the new version of the service we left out this functionality because
- we were still awaiting a fix
- we knew both FRAE and WEX depend on this so wanted to implement a shared solution
With the creation of [defra-ruby-area](https://github.com/DEFRA/defra-ruby-area) we now have that shared solution.
So this change covers everything needed to integrate the gem and identify the area as part of the new registration journey.

Identify EA Administrative Area for new regs.

---

app/views/waste_exemptions_engine/register_in_wales_forms/new.html.erb

https://eaflood.atlassian.net/browse/RUBY-647
Our QA @andrewhick spotted in testing that the link to NRW on the register in wales page was no longer working. When clicked users were presented with a 404 from the NRW site.
The issue appears to be that they no longer have a root waste exemptions page. They now have
- [Register or renew your waste exemptions: agricultural premises](https://naturalresources.wales/permits-and-permissions/waste-permitting/register-or-renew-your-waste-exemptions-agricultural-premises/)
- [Register or renew your waste exemptions: non-agricultural premises](https://naturalresources.wales/permits-and-permissions/waste-permitting/register-or-renew-your-waste-exemptions-non-agricultural-waste/)
There was some discussion about whether we needed to update our page to …

Fix broken link to NRW waste exemptions page

---

spec/models/waste_exemptions_engine/address_spec.rb

Some tests are leaving the DB dirty with Addresses, making the model's spec fail.
We have already witnessed some instance of those random failures, such as: https://travis-ci.com/DEFRA/waste-exemptions-engine/builds/128905376
This code should prevent that from happening again

Clean db from Addresses

---

app/models/waste_exemptions_engine/address.rb
spec/models/waste_exemptions_engine/address_spec.rb

The various scopes on Address to identify those with missing x & y, and area information is used in jobs to ensure they are populated. The aim is to try and identify the EA area for each registration we have.
The address we use to determine this though is the **site**. Where the site is located is what determines the a registration's area. So we don't care if the x & y or area is missing on the other addresses. We only care they are populated for the site address.

Restrict address missing scopes to site addresses

---

app/models/waste_exemptions_engine/address.rb
spec/models/waste_exemptions_engine/address_spec.rb

This reverts commit 5556ffacd07d339af54d34deb28c347ac2810683.
The change made was due to a lack of understanding about scopes, and the fact that because we use enums that we get the scope `:site` for free on the address.
So rather than changing the current scopes to include a condition to test for the address type, instead we can just chain scopes together
```ruby
WasteExemptionsEngine::Address.site.missing_area
```
This gives the same result as `sites_missing_area`. By reverting this change our scopes become flexible again, and we can do things in a much more 'rails' way.

Revert "Restrict address missing scopes to site addresses (#365)"

---

app/forms/waste_exemptions_engine/site_address_manual_form.rb
app/views/waste_exemptions_engine/site_address_manual_forms/new.html.erb
spec/forms/waste_exemptions_engine/site_address_manual_form_spec.rb
spec/requests/waste_exemptions_engine/site_address_manual_forms_spec.rb

Following on: https://github.com/DEFRA/waste-exemptions-engine/pull/341/files
This apply the same refactoing to the site address manual form.
The goal is to make use of rails-ness on these forms, so we want them to name the attributes as per TransientAddress attributes. This will allow the use of strong parameters and less code to custom-submit these forms rather than letting rails do the job for us :D

Site Address manual form refactoring

---

app/forms/waste_exemptions_engine/operator_address_manual_form.rb
app/views/waste_exemptions_engine/operator_address_manual_forms/new.html.erb
spec/forms/waste_exemptions_engine/operator_address_manual_form_spec.rb
spec/requests/waste_exemptions_engine/operator_address_manual_forms_spec.rb

Following on: https://github.com/DEFRA/waste-exemptions-engine/pull/341/files
This apply the same refactoing to the operator address manual form.
The goal is to make use of rails-ness on these forms, so we want them to name the attributes as per TransientAddress attributes. This will allow the use of strong parameters and less code to custom-submit these forms rather than letting rails do the job for us :D

Operator Address manual form refactoring

---

app/forms/concerns/waste_exemptions_engine/can_create_address_from_finder_data.rb
app/forms/waste_exemptions_engine/address_lookup_form_base.rb
app/forms/waste_exemptions_engine/contact_address_lookup_form.rb
app/forms/waste_exemptions_engine/operator_address_lookup_form.rb
app/forms/waste_exemptions_engine/site_address_lookup_form.rb
spec/support/shared_examples/forms/address_lookup_form.rb

Part of the form refactoring.
In this case I have kept the base Lookup Forms class, but I have moved the implementation of the submit method in the children.
This will allow easier refactoring for the rest of the class.
The create address from urpn function have moved to a concern and has no more any dependency with methods defined in the including classes.
Use delegate and alias instead of attribute accessors.

Refactor address lookups form

---

app/forms/waste_exemptions_engine/contact_position_form.rb
app/views/waste_exemptions_engine/contact_position_forms/new.html.erb
spec/forms/waste_exemptions_engine/contact_position_form_spec.rb
spec/requests/waste_exemptions_engine/contact_position_forms_spec.rb

Rename `position` to `contact_position` to be in-line with the models' attribute name.

Contact Position Form refactoring

---

app/forms/waste_exemptions_engine/operator_address_manual_form.rb

Closes: https://eaflood.atlassian.net/browse/RUBY-713
While doing the forms refactoring I forgot to delegate or populate the business type that is needed on the operator address.

Delegate business type to transient registration

---

spec/models/waste_exemptions_engine/address_spec.rb

This is just some housekeeping. It was spotted that we were not being consistent in our tests for the scopes on the Address model in a recent commit to add a `with_postcode` scope.
So this change updates all the tests to use `match_array` rather than having separate expectations to check the size and content of the returned result.

Update Address scope tests to use match_array

---

Gemfile.lock
waste_exemptions_engine.gemspec

https://github.com/DEFRA/waste-exemptions-front-office/pull/256
https://github.com/DEFRA/waste-exemptions-back-office/pull/435
We just had Dependabot update the version of [defra_ruby_validators](https://github.com/DEFRA/defra-ruby-validators) used by the front and back office under the guise of updating the engine.
This broke the apps, so to protect against this in future we are using pessimistic versioning for the gem to ensure the apps don't try and take a version they're not ready for.

Set version of defra_ruby_validators

---

app/views/waste_exemptions_engine/contact_address_lookup_forms/new.html.erb
app/views/waste_exemptions_engine/operator_address_lookup_forms/new.html.erb
app/views/waste_exemptions_engine/site_address_lookup_forms/new.html.erb

A recent refectoring had a small omission in each of the postcode lookup forms (operator, contact and site).
We needed to tell the view that the select i.e. the field was for the form we have passed in. Without the `f.` the view was just basing the element names on whatever the attribute was called, omitting the form part and so breaking our the logic in our `BaseForm` which passes on the forms params to the form instance.
That is a convuloted way of trying to say we had a typo 😳🤦!

Fix missing `f.` in postcode lookup views

---

spec/factories/address.rb
spec/factories/registration.rb
spec/factories/transient_address.rb

Ahead of the need to add some tests specific to site addresses we spotted that the current `:site_address` trait sets a couple of other fields, not just the address type. This is different to the `:operator_address` and ':contact_address` traits which just set the address type
We need to set the address type as part of some tests we are looking to add. But we also need to be able to specify creating the 3 different kinds of site address; from grid reference, from address lookup, and from address manual.
In its current state we would not have been able to reuse the trait. With this refactor we can, plus
- its now consistent with the other address type traits
- the new trait is more descriptive of what is actually going on

Refactor the site address trait in Factories

---

app/forms/concerns/waste_exemptions_engine/can_clear_address_finder_error.rb
app/forms/waste_exemptions_engine/contact_address_manual_form.rb
app/forms/waste_exemptions_engine/operator_address_manual_form.rb
app/forms/waste_exemptions_engine/site_address_manual_form.rb

Our manual addres forms have a couple of peculiarities, all to deal with the transient nature of the postcode.
Since the postcode is captured in a different screen, the address manual form has to decide wheter or not to show the in-store manual address depending on the fact that the postcode has changed or has remained the same. For this reson, in this cases, we are setting the attribute on the in-memory transient registration to `nil` wheter the postcode doesn't match the stored one, so that we can be consistent and delegate everything else.

Manual address forms delegate refactoring

---

app/forms/waste_exemptions_engine/site_address_manual_form.rb

This is a little bug for which we are pre-populating the site address with contact address temp postcode.

Fix typo: site instead of contact

---

Gemfile.lock
waste_exemptions_engine.gemspec

https://github.com/codeclimate/test-reporter/issues/418
On 28 Jan 2020 [SimpleCov 0.18.0](https://github.com/colszowka/simplecov/releases/tag/v0.18.0) was released. Though it's generating code coverage for us, its changed the JSON format of the `/coverage/.resultset.json` CodeClimate's [cc-test-reporter](https://github.com/codeclimate/test-reporter) appears to rely on.
<details>
<summary>Format before</summary>
```json
{
"RSpec": {
"coverage": {
"/path/to/my/file.rb": [
null,
null,
1
]
},
"timestamp": 1580226312
}
}
```
</details>
<details>
<summary>Format after</summary>
```json
{
"RSpec": {
"coverage": {
"/path/to/my/file.rb": {
"lines": [
null,
null,
1,
null
],
"branches": {
}
}
},
"timestamp": 1580299988
}
}
```
</details>
When **cc-test-reporter** is called in the `after_script` hook …

Temp. fix for cc-test-reporter & SimpleCov 0.18

---

Gemfile
Gemfile.lock
lib/waste_exemptions_engine.rb
lib/waste_exemptions_engine/engine.rb
spec/dummy/config/initializers/waste_exemptions_engine.rb
waste_exemptions_engine.gemspec

Whilst working on an issue for the [Flood Risk Activity Exemptions service](https://github.com/DEFRA/ruby-services-team/tree/master/services/frae) we came across an [issue](https://github.com/DEFRA/flood-risk-engine/pull/312) with Airbrake.
We wanted to add a new Rake task, and we wanted to apply our new pattern of ensuring Airbrake is closed when the task exits to ensure any errors are reported. The problem was due to the age of the Airbrake gem being used this caused an error in FRAE we hadn't seen in WEX and WCR.
So for reasons outlined in [FRAE PR 312](https://github.com/DEFRA/flood-risk-engine/pull/312) we came up with [defra-ruby-alert](https://github.com/DEFRA/defra-ruby-alert). The idea is going forward this will provide a single interface for configuring Airbrake and ensure the …

Switch airbrake mgmt to defra-ruby-alert

---

Gemfile.lock

This replaces PR #435 dependabot opened which for some reason is updating a bunch of other stuff as well as defra_ruby_email.
The main issue is its updated sprockets to 4.0.0 but that version requires a minimum ruby version of 2.5.0

Bump defra_ruby_email from 0.1.0 to 0.2.0

---

app/views/waste_exemptions_engine/start_forms/new.html.erb

This fixes a bug for which we are failing to apply the correct form error group class to the form group in the start form page

Fix visual bug on error message

---

spec/support/vcr.rb

We still want to keep VCR in this project. However, re-recording every fortnight is too big a maintenance overhead,   and we have other ways of detecting breaking changes now.
This change removes the automatic two-week expiry, so cassettes will remain as they are until the request is modified or we decide to update them.

Don't expire VCR cassettes

---

spec/requests/waste_exemptions_engine/confirm_edit_cancelled_forms_spec.rb
spec/requests/waste_exemptions_engine/edit_cancelled_forms_spec.rb
spec/requests/waste_exemptions_engine/edit_complete_forms_spec.rb
spec/requests/waste_exemptions_engine/edit_forms_spec.rb
spec/requests/waste_exemptions_engine/errors_spec.rb
spec/requests/waste_exemptions_engine/main_people_forms_spec.rb
spec/requests/waste_exemptions_engine/renew_spec.rb
spec/requests/waste_exemptions_engine/renew_with_changes_forms_spec.rb
spec/requests/waste_exemptions_engine/renew_without_changes_forms_spec.rb
spec/requests/waste_exemptions_engine/renewal_complete_forms_spec.rb
spec/requests/waste_exemptions_engine/renewal_start_forms_spec.rb
spec/requests/waste_exemptions_engine/site_grid_reference_forms_spec.rb
spec/requests/waste_exemptions_engine/start_forms_spec.rb
spec/support/shared_examples/requests/get_form.rb
spec/support/shared_examples/requests/go_back.rb
spec/support/shared_examples/requests/post_form.rb
spec/support/shared_examples/requests/skip_to_manual_address.rb

We decided a while ago that we whould compact all scenarios in the same context to one, in order to make only one request per context and so speed up our test suite. This apply this principle to the test suite.
Before: 
After:

Refactor request tests to compact them

---

.travis.yml

Problem: 
Since last week all our builds are failing. 
The main error is:
```
$ gem install -v 1.17.3 bundler --no-rdoc --no-ri
ERROR:  While executing gem ... (OptionParser::InvalidOption)
invalid option: --no-rdoc
The command "gem install -v 1.17.3 bundler --no-rdoc --no-ri" failed and exited with 1 during .
```
Visibile in: https://travis-ci.com/github/DEFRA/waste-exemptions-engine/builds/166643334
The only difference in our builds, seems to be in the binary version of ruby that travis install. Before the breakage, we could observe from the logs that we were installing ruby from https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.4.2.tar.bz2  (https://travis-ci.com/github/DEFRA/waste-exemptions-engine/builds/165727465)
When the breakage started happening, we could observe that the …

Remove options from bundler

---

app/validators/concerns/waste_exemptions_engine/can_add_validation_errors.rb
app/validators/concerns/waste_exemptions_engine/can_validate_length.rb
app/validators/concerns/waste_exemptions_engine/can_validate_presence.rb
app/validators/concerns/waste_exemptions_engine/can_validate_selection.rb
app/validators/waste_exemptions_engine/address_validator.rb
app/validators/waste_exemptions_engine/base_validator.rb
app/validators/waste_exemptions_engine/exemptions_validator.rb
app/validators/waste_exemptions_engine/manual_address_validator.rb
app/validators/waste_exemptions_engine/matching_email_validator.rb
app/validators/waste_exemptions_engine/person_name_validator.rb
app/validators/waste_exemptions_engine/postcode_validator.rb

https://eaflood.atlassian.net/browse/RUBY-1138
This update fixes a bug introduced with the Rails 6 upgrade that was preventing the postcode lookup page from displaying the 'skip to manual address' link when the right error was triggered.
The fix follows the same model as used in waste carriers here: https://github.com/DEFRA/waste-carriers-engine/pull/875

Update validator error message syntax with concern

---

app/models/waste_exemptions_engine/feature_toggle.rb
bin/rails
db/migrate/20200629141525_create_feature_toggle.rb
spec/dummy/db/schema.rb
spec/factories/feature_toggle.rb
spec/models/waste_exemptions_engine/feature_toggle_spec.rb

From: https://eaflood.atlassian.net/browse/RUBY-1139
This upgrade the feature toggle to be a proper model.
It also fixes the content of the `bin/rails` file which was pointing to the wrong files.
The old Feature Toggle functionality and interface as stayied the same. To achieve 0 downtime we will fall back to the content of the yml if we can't find a match for a given feature on the database. Once this is merged and deployed, we can create the records using the back-office interface and then at the subsequent deploy we can cleanup the code in the model that fallsback to the content of the config file.

Updgrade Feature Toggle to proper model

---

Gemfile.lock
app/services/waste_exemptions_engine/notify_service.rb
lib/waste_exemptions_engine.rb
spec/cassettes/notify_test.yml
spec/dummy/config/initializers/waste_exemptions_engine.rb
spec/services/waste_exemptions_engine/notify_service_spec.rb
waste_exemptions_engine.gemspec

This PR installs the Notify gem for Ruby and adds a test class to send basic test emails.

Add initial test implementation of Notify

---

db/migrate/20200629141525_create_feature_toggle.rb
spec/dummy/db/schema.rb

When testing this, we found that if an earlier version of the feature_toggle table existed, the deployment would break.

Stop feature toggle migration from breaking prod data

---

app/controllers/waste_exemptions_engine/contact_position_forms_controller.rb

https://eaflood.atlassian.net/browse/RUBY-1263
The controller for the contact position form did not have the `contact_position` attribute set as an allowed param. This meant that it was not saved when the form was submitted. This didn't raise an error because leaving the form blank is also a valid response.

Allow contact position form to persist data

---

app/models/concerns/waste_exemptions_engine/can_be_ordered_by_state_and_exemption_id.rb
app/models/waste_exemptions_engine/registration_exemption.rb
app/models/waste_exemptions_engine/transient_registration_exemption.rb
app/presenters/waste_exemptions_engine/notify_confirmation_letter_presenter.rb
app/services/waste_exemptions_engine/notify_confirmation_letter_service.rb
config/locales/confirmation_letters.en.yml
spec/cassettes/notify_confirmation_letter.yml
spec/factories/address.rb
spec/factories/registration.rb
spec/factories/registration_exemption.rb
spec/models/waste_exemptions_engine/registration_exemption_spec.rb
spec/presenters/waste_exemptions_engine/notify_confirmation_letter_presenter_spec.rb
spec/services/waste_exemptions_engine/notify_confirmation_letter_service_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1248
In order to send letters when registrations are completed, rather than on an overnight schedule, we need to be able to send them from *wherever* they are completed. This means both front and back office, so it's time to move this code into the engine.
This had a lot of dependencies on other bits of code so I had to move that over too, along with some slight refactoring to avoid deprecation warnings.

Move Notify confirmation letter code from BO to engine

---

lib/waste_exemptions_engine.rb
spec/dummy/config/initializers/waste_exemptions_engine.rb

https://eaflood.atlassian.net/browse/RUBY-1208
Previously the AD email address was hardcoded into the back office.
This is a pain for testing and flexibility, and inconsistent with waste carriers, so we should allow it to be configured in the engine initialiser instead. This will let us set a default if we like or override it with an environment variable.

Configure AD email in engine initialiser

---

app/services/waste_exemptions_engine/registration_completion_service.rb
spec/factories/new_registration.rb
spec/services/waste_exemptions_engine/registration_completion_service_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1248
When a user registers and does not have their own contact email, we should send a confirmation letter through Notify instead.
This only applies if the registration's contact email is set to the AD WEX email.

Send confirmation letter to fully AD users on completion

---

app/helpers/waste_exemptions_engine/plurals_helper.rb
app/views/waste_exemptions_engine/registration_complete_forms/new.html.erb
app/views/waste_exemptions_engine/renewal_complete_forms/new.html.erb
config/locales/forms/registration_complete_forms/en.yml
config/locales/forms/renewal_complete_forms/en.yml
spec/helpers/waste_exemptions_engine/plurals_helper_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1248
The registration and renewal confirmation pages always said that we had sent a confirmation email, even when we sent a letter instead. This PR fixes that.

Display correct text about confirmation letter or email

---

db/migrate/20210308160306_remove_ad_letter_exports.rb
spec/dummy/db/schema.rb

https://eaflood.atlassian.net/browse/RUBY-1272
We are removing the old letter export functionality since we now have Notify in place. This means we no longer need to keep these tables and models for storing letter info.

Drop letter export tables

---

.github/workflows/ci.yml
app/services/waste_exemptions_engine/address_lookup_service.rb
config/initializers/defra_ruby_address.rb
spec/cassettes/postcode_no_matches.yml
spec/cassettes/postcode_valid.yml
spec/support/vcr.rb

https://eaflood.atlassian.net/browse/RUBY-1340
As part of updating our OS Places API Endpoint, we needed to update to the later version of the address facade.
This requires some additional config, which this update adds.

Switch to EA Address Facade v1.1

---

app/forms/waste_exemptions_engine/address_lookup_form_base.rb

We now receive a lot more data from the address lookup, but we don't need a lot of it! So it now becomes easier to specify the keys we want to use, rather than the ones we want to exclude.

Fix unsubmittable address lookup form

---

app/helpers/waste_exemptions_engine/application_helper.rb
app/views/waste_exemptions_engine/shared/_error_summary.html.erb
spec/dummy/db/schema.rb
spec/helpers/waste_exemptions_engine/application_helper_spec.rb

https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-1727
Here we have updated the page titles to change when an error is generated. This allows screen readers to give a better description to the user on the pages status.
The titles will now read <% Error - What do you want to do? - Register your waste exemptions - GOV.UK %> when an error has been generated.
Four test has been written in application_helper_spec to check the helper method for titles and to check the errors in titles.

Adding 'Error' in the page title when an error is generated 

---

app/controllers/waste_exemptions_engine/check_contact_email_forms_controller.rb
app/forms/waste_exemptions_engine/check_contact_email_form.rb
app/models/concerns/waste_exemptions_engine/can_use_new_registration_workflow.rb
app/models/waste_exemptions_engine/transient_registration.rb
app/views/waste_exemptions_engine/check_contact_email_forms/new.html.erb
config/locales/forms/check_contact_email_forms/en.yml
config/routes.rb
db/migrate/20220401131927_add_temp_reuse_applicant_email_to_transient_registrations.rb
spec/cassettes/w3c_valid_content/check_contact_email_forms_spec/when-the-registration-is-in-the-correct-state.yml
spec/dummy/db/schema.rb
spec/factories/forms/check_contact_email_form.rb
spec/forms/waste_exemptions_engine/check_contact_email_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/check_contact_email_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/check_contact_phone_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/contact_email_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/contact_phone_form_spec.rb
spec/requests/waste_exemptions_engine/check_contact_email_forms_spec.rb

This change introduces a step in the new exemption registration journey to allow the user to reuse the applicant email address as the contact email address.
https://eaflood.atlassian.net/browse/RUBY-1841

Optionally use applicant email as contact email

---

app/controllers/waste_exemptions_engine/check_contact_address_forms_controller.rb
app/forms/waste_exemptions_engine/check_contact_address_form.rb
app/models/concerns/waste_exemptions_engine/can_use_new_registration_workflow.rb
app/models/waste_exemptions_engine/transient_registration.rb
app/views/waste_exemptions_engine/check_contact_address_forms/new.html.erb
config/locales/forms/check_contact_address_forms/en.yml
config/routes.rb
db/migrate/20220401153506_add_temp_reuse_operator_address_to_transient_registrations.rb
spec/cassettes/w3c_valid_content/check_contact_address_forms_spec/when-the-registration-is-in-the-correct-state.yml
spec/dummy/db/schema.rb
spec/factories/forms/check_contact_address_form.rb
spec/forms/waste_exemptions_engine/check_contact_address_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/check_contact_email_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/contact_email_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/contact_postcode_form_spec.rb
spec/requests/waste_exemptions_engine/check_contact_address_forms_spec.rb

This change allows the user to reuse the operator address as the contact address. If the user takes this option, a new contact address is created, copying the relevant attributes of the operator address.
https://eaflood.atlassian.net/browse/RUBY-1842

Allow reuse of operator address as contact address

---

.github/workflows/ci.yml

This change forces GitHub CI to run apt-get update before trying to install dependencies. It is currently failing to find the required versions of some ubuntu libraries, possibly because of a stale mirror site. It may be desirable to revert this change in future if the GitHub / ubuntu issue is resolved.
https://eaflood.atlassian.net/browse/RUBY-1872

Force github to run apt-get update before installing dependencies

---

app/models/waste_exemptions_engine/transient_registration.rb
app/services/waste_exemptions_engine/refresh_companies_house_name_service.rb
db/migrate/20220510134655_add_temp_use_registered_company_details_to_transient_registrations.rb
db/migrate/20220524150518_add_companies_house_updated_at_to_transient_registrations.rb
lib/defra_ruby_companies_house.rb
spec/dummy/db/schema.rb
spec/lib/defra_ruby_companies_house_spec.rb
spec/services/waste_exemptions_engine/refresh_companies_house_name_service_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1877
Here we have the refresh service for the company house API. This allows the back office users to manually refresh the registered company name without manually entering a name in

Refresh service for companies house name

---

app/controllers/waste_exemptions_engine/check_registered_name_and_address_forms_controller.rb
app/forms/waste_exemptions_engine/check_registered_name_and_address_form.rb
app/views/waste_exemptions_engine/check_registered_name_and_address_forms/inactive_company.html.erb
config/locales/forms/check_registered_name_and_address_forms/en.yml
lib/defra_ruby_companies_house.rb
spec/cassettes/w3c_valid_content/check_registered_name_and_address_forms_spec/when-the-company-status-is-no-longer-active.yml
spec/fixtures/files/inactive_companies_house_response.json
spec/lib/defra_ruby_companies_house_spec.rb
spec/requests/waste_exemptions_engine/check_registered_name_and_address_forms_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1885
Here we are adding an error partial for when a company is no longer active during its renewal.
This is currently for renewals using the magic link

Company house inactive error

---

app/controllers/waste_exemptions_engine/check_registered_name_and_address_forms_controller.rb
app/forms/waste_exemptions_engine/check_registered_name_and_address_form.rb
app/views/waste_exemptions_engine/check_registered_name_and_address_forms/companies_house_down.html.erb
config/locales/forms/check_registered_name_and_address_forms/en.yml
spec/requests/waste_exemptions_engine/check_registered_name_and_address_forms_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1886
Here we add a template informing the users when the companies house API is down to try again later.

Added in company house down page for API issues

---

app/models/concerns/waste_exemptions_engine/can_use_renewing_registration_workflow.rb
spec/models/waste_exemptions_engine/renewing_registration_workflow_state/operator_postcode_form_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1999
Here we have the changes to the back navigation for operator_postcode_form. Previously it was going back to operator name form even when the business type was a company. This change stops that and navigates it back to the correct page.

Change to back navigation for renewals

---

app/controllers/waste_exemptions_engine/applicant_email_forms_controller.rb
app/controllers/waste_exemptions_engine/contact_email_forms_controller.rb
app/forms/waste_exemptions_engine/applicant_email_form.rb
app/forms/waste_exemptions_engine/check_your_answers_form.rb
app/forms/waste_exemptions_engine/contact_email_form.rb
app/models/concerns/waste_exemptions_engine/can_use_new_registration_workflow.rb
app/validators/waste_exemptions_engine/optional_email_form_validator.rb
app/validators/waste_exemptions_engine/optional_email_validator.rb
app/views/waste_exemptions_engine/applicant_email_forms/new.html.erb
app/views/waste_exemptions_engine/contact_email_forms/new.html.erb
config/locales/forms/applicant_email_forms/en.yml
config/locales/forms/contact_email_forms/en.yml
lib/waste_exemptions_engine.rb
spec/forms/waste_exemptions_engine/applicant_email_form_spec.rb
spec/forms/waste_exemptions_engine/check_your_answers_form_spec.rb
spec/forms/waste_exemptions_engine/contact_email_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/check_contact_phone_form_spec.rb
spec/models/waste_exemptions_engine/new_registration_workflow_state/contact_phone_form_spec.rb
spec/support/shared_examples/forms/optional_email_form.rb
spec/support/shared_examples/models/transient_registration_workflow_state/a_simple_bidirectional_transition.rb
spec/validators/waste_exemptions_engine/optional_email_form_validator_spec.rb
spec/validators/waste_exemptions_engine/optional_email_validator_spec.rb

This change makes applicant and contact email addresses optional in the back-office only. Leaving the contact email blank will ensure that the contact receives a letter instead of an email (implemented separately under https://eaflood.atlassian.net/browse/RUBY-1997). 
This change also ensures that the page which presents the option to reuse the applicant email as the contact email is skipped if applicant email has not been populated.
https://eaflood.atlassian.net/browse/RUBY-1719

Optional applicant and contact email addresses

---

app/controllers/waste_exemptions_engine/check_registered_name_and_address_forms_controller.rb
spec/cassettes/w3c_valid_content/check_registered_name_and_address_forms_spec/when-the-company-number-is-invalid.yml
spec/requests/waste_exemptions_engine/check_registered_name_and_address_forms_spec.rb

https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-1885
This change means that during a renewal if the company number is invalid it will show the user the 'inactive company' page rather than the 'companies house down' one previously.

Companies House number validation

---

app/helpers/waste_exemptions_engine/plurals_helper.rb
app/presenters/waste_exemptions_engine/notify_confirmation_letter_presenter.rb
app/services/waste_exemptions_engine/notify_confirmation_letter_service.rb
app/services/waste_exemptions_engine/registration_completion_service.rb
config/locales/confirmation_letters.en.yml
spec/cassettes/registration_complete_letter_sent.yml
spec/cassettes/w3c_valid_content/registration_complete_forms_spec/when-the-registration-is-in-the-correct-state.yml
spec/factories/new_registration.rb
spec/helpers/waste_exemptions_engine/plurals_helper_spec.rb
spec/presenters/waste_exemptions_engine/notify_confirmation_letter_presenter_spec.rb
spec/services/waste_exemptions_engine/registration_completion_service_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1997
Here we have the changes to allow letters to be sent to registrations without an email address. 
In WEX there are two emails address captured, applicant_email and contact_email. 
These changes mean letters are sent to any emails that are nil value instead of the NCCC email address.
A plural helper method was also affected with the change, and has been updated to allow for a nil address.

Send letters to contacts with no email address

---

app/views/waste_exemptions_engine/registration_complete_forms/new.html.erb
config/locales/forms/registration_complete_forms/en.yml
spec/helpers/waste_exemptions_engine/application_helper_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1927
Here we have the changes for the registered screen adding the date to the exemption expiry.

Adding date to registered screen

---

app/forms/waste_exemptions_engine/applicant_email_form.rb
app/forms/waste_exemptions_engine/contact_email_form.rb
app/validators/waste_exemptions_engine/optional_email_form_validator.rb
spec/dummy/config/initializers/waste_exemptions_engine.rb
spec/dummy/db/schema.rb
spec/support/shared_examples/forms/optional_email_form.rb

https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-2051
This change resolves a potential issue where submitting the contact_email or applicant_email form with a blank contact_email/applicant_email field and selecting the "No email" option would result in the email value of "" (empty string) instead of nil. The value should be nil in all cases where a valid email value has not been provided.

Fix blank/nil email options

---

app/models/waste_exemptions_engine/new_registration.rb
app/services/waste_exemptions_engine/registration_completion_service.rb
db/migrate/20221004145505_add_assistance_mode_to_transient_registrations.rb
spec/dummy/db/schema.rb
spec/models/waste_exemptions_engine/new_registration_spec.rb
spec/services/waste_exemptions_engine/registration_completion_service_spec.rb

This change tracks partially-assisted registrations for inclusion in the Boxi export.
https://eaflood.atlassian.net/browse/RUBY-2002

Track partial assisted digital

---

.rubocop.yml
Gemfile.lock
app/services/waste_exemptions_engine/exemption_deregistration_service.rb
config/locales/en.yml
spec/services/waste_exemptions_engine/exemption_deregistration_service_spec.rb

This change adds an exemption deregistration service which handles null, full and partial de-registrations:
* If the `transient_registration` has the same exemptions as the original registration, nothing happens.
* If the `transient_registration` has no exemptions, all exemptions  for the registration are deactivated with a `deregistered_at` value of today.
* If the `transient_registration` has a subset of the exemptions of the original registration, all unselected exemptions are set to "inactive" with a `deregistered_at` date of today and a `state` of "inactive". All selected exemptions remain unchanged.
https://eaflood.atlassian.net/browse/RUBY-2356

exemption deregistration service

---

Gemfile.lock

This change drops a migration which would have deleted registration.deregistration_email_sent_at.
https://eaflood.atlassian.net/browse/RUBY-2481

fix deregistration_email_sent_at

---

app/controllers/waste_exemptions_engine/front_office_edit_forms_controller.rb
spec/requests/waste_exemptions_engine/front_office_edit_forms_spec.rb

WAF is configured to not allow 422 responses, so we return a 404 instead for an expired token.
https://eaflood.atlassian.net/browse/RUBY-2643

Return HTTP 404 instead of 422 for an expired edit_token

---

db/migrate/20231107131130_add_index_to_transient_registrations_created_at.rb
spec/dummy/db/schema.rb
spec/presenters/waste_exemptions_engine/registration_details_presenter_spec.rb

Introduces a database index to enhance query performance for transient registrations cleanup job,
potentially resolving the memory issues encountered during scheduled task execution.

[RUBY-2789] Optimize cleanup task by adding index to created_at in transient_registrations

---

Gemfile.lock
app/models/waste_exemptions_engine/transient_registration.rb
app/services/waste_exemptions_engine/safe_copy_registration_attributes_service.rb
spec/services/waste_exemptions_engine/safe_copy_registration_attributes_service_spec.rb

This change is to reduce the risk of a registration completion failing due to a transient_registration having an attribute which is not supported on the registration. This has happened in the past where a transient_registration is created before a deployment with an attribute which is no longer present on the registration after the deployment.
https://eaflood.atlassian.net/browse/RUBY-2861

Add SafeCopyRegistrationAttributesService
