- app/controllers/waste_exemptions_engine/operator_name_forms_controller.rb
- app/forms/waste_exemptions_engine/operator_name_form.rb
- app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
- app/validators/waste_exemptions_engine/operator_name_validator.rb
- app/views/waste_exemptions_engine/operator_name_forms/new.html.erb
- config/locales/forms/operator_name_forms/en.yml
- config/routes.rb
- db/migrate/20181214164534_add_operator_name_to_enrollments.rb
Copies code from waste carriers renewals for capturing the operator name (based on renewals company name) who is responsible for the waste operation.
> Add operator name page

- app/controllers/waste_exemptions_engine/contact_name_forms_controller.rb
- app/forms/waste_exemptions_engine/contact_name_form.rb
- app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
- app/views/waste_exemptions_engine/contact_name_forms/new.html.erb
- config/locales/forms/contact_name_forms/en.yml
- config/routes.rb
- db/migrate/20181217221625_add_contact_name_to_enrollments.rb
This reuses the applicant name logic to create a contact name page.
> Add contact name page

- app/controllers/waste_exemptions_engine/contact_phone_forms_controller.rb
- app/forms/waste_exemptions_engine/contact_phone_form.rb
- app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
- app/views/waste_exemptions_engine/contact_phone_forms/new.html.erb
- config/locales/forms/contact_phone_forms/en.yml
- config/routes.rb
- db/migrate/20181217230738_add_contact_phone_to_enrollments.rb
This continues to follow the pattern for our pages and workflow, adding the contact telephone number page.
> Add contact telephone number page

- app/controllers/waste_exemptions_engine/contact_email_forms_controller.rb
- app/forms/waste_exemptions_engine/contact_email_form.rb
- app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
- app/views/waste_exemptions_engine/contact_email_forms/new.html.erb
- config/locales/forms/contact_email_forms/en.yml
- config/routes.rb
- db/migrate/20181217232226_add_contact_email_to_enrollments.rb
This continues to follow the pattern for our pages and workflow, adding the contact email page.
> Add contact email page

- app/views/waste_exemptions_engine/registration_number_forms/new.html.erb
It appears I let the find and replace change things it shouldn't in PR #32. This change rectifies the issue which caused the company registration page to error.
> Fix broken company registration number page

- Gemfile.lock
- spec/cassettes/company_no_valid.yml
- spec/dummy/config/environments/test.rb
- spec/rails_helper.rb
- waste_exemptions_engine.gemspec
We've decided to add the Bullet gem to highlight unoptimised queries when the test suite executes.
> Add Bullet as a dependency and integrate into RSpec

- app/views/waste_exemptions_engine/pdfs/privacy_policy.html
https://eaflood.atlassian.net/browse/RUBY-216
Update the content of the HTML file used to generate the PDF for email attachment.
Changes are made to reflect the latest legislation requirement as per April, 2019
> Update privacy policy text

- config/locales/forms/edit_forms/en.yml
This fix a capital letter typo for the Edit form
> Fix capital letter on translation

- app/views/waste_exemptions_engine/pdfs/privacy_policy.html
Now we have our release date we know when this version of the privacy policy will go live. As such this change updates the date to match our expected release date.
> Update date on privacy policy PDF

- config/locales/forms/renew_with_changes_forms/en.yml
https://eaflood.atlassian.net/browse/RUBY-241
The content for this paragraph was updated following a review of the wireframe.
> Make a minor content amend to 'renew with changes' page

- app/views/waste_exemptions_engine/renew_without_changes_forms/new.html.erb
- config/locales/forms/renew_without_changes_forms/en.yml
- spec/cassettes/w3c_valid_content/renew_without_changes_forms_spec.yml
From: https://eaflood.atlassian.net/browse/RUBY-498
Add text as per SPOT wireframe
> Style renew without changes page

- app/controllers/waste_exemptions_engine/renews_controller.rb
- app/helpers/waste_exemptions_engine/renews_helper.rb
- app/views/waste_exemptions_engine/renews/already_renewed.html.erb
- config/locales/forms/renews/en.yml
- spec/cassettes/w3c_valid_content/renew_spec.yml
- spec/requests/waste_exemptions_engine/renew_spec.rb
From: https://eaflood.atlassian.net/browse/RUBY-511
Prevent the user from renewing a registration that has already been renewed and presents them an informative page.
> Prevent user to renew again

- app/controllers/waste_exemptions_engine/renews_controller.rb
- app/helpers/waste_exemptions_engine/renews_helper.rb
- app/views/waste_exemptions_engine/renews/already_renewed.html.erb
- app/views/waste_exemptions_engine/renews/invalid_magic_link.html.erb
- config/locales/forms/renews/en.yml
- spec/cassettes/w3c_valid_content/renew_spec/when-a-token-is-invalid.yml
- spec/requests/waste_exemptions_engine/renew_spec.rb
From: https://eaflood.atlassian.net/browse/RUBY-533
Add missing token custom error page
> Add custom error page on missing token

- app/forms/waste_exemptions_engine/data_overview_form.rb
This was raising an error when we tried to merge the engine update: https://github.com/DEFRA/waste-exemptions-back-office-ta/pull/325
> Optimise query to appease Bullet

- config/locales/forms/applicant_email_forms/en.yml
- config/locales/forms/applicant_name_forms/en.yml
- config/locales/forms/applicant_phone_forms/en.yml
- config/locales/forms/contact_address_lookup_forms/en.yml
- config/locales/forms/contact_address_manual_forms/en.yml
- config/locales/forms/contact_email_forms/en.yml
- config/locales/forms/contact_phone_forms/en.yml
- config/locales/forms/contact_position_forms/en.yml
- config/locales/forms/contact_postcode_forms/en.yml
- config/locales/forms/is_a_farmer_forms/en.yml
- config/locales/forms/location_forms/en.yml
- config/locales/forms/register_in_northern_ireland_forms/en.yml
- config/locales/forms/register_in_scotland_forms/en.yml
- config/locales/forms/register_in_wales_forms/en.yml
- config/locales/forms/registration_number_forms/en.yml
- config/locales/forms/renews/en.yml
- config/locales/forms/site_address_lookup_forms/en.yml
- config/locales/forms/site_address_manual_forms/en.yml
- config/locales/forms/site_postcode_forms/en.yml
From: https://eaflood.atlassian.net/browse/RUBY-501
Changes to header's text in the registration process forms.
> Copy changes to registration forms

- config/locales/forms/renews/en.yml
- spec/cassettes/w3c_valid_content/renew_spec/when-a-registration-is-past-the-renewal-window.yml
https://eaflood.atlassian.net/browse/RUBY-496
We decided to remove the mention of the renewal window and simplify the content.
> Amend text on 'too late to renew' page

- config/locales/forms/operator_name_forms/en.yml
From: https://eaflood.atlassian.net/browse/RUBY-592
> Add missin translation for LLP

- app/forms/waste_exemptions_engine/applicant_phone_form.rb
- app/views/waste_exemptions_engine/applicant_phone_forms/new.html.erb
- config/locales/forms/applicant_phone_forms/en.yml
- spec/forms/waste_exemptions_engine/applicant_phone_form_spec.rb
- spec/requests/waste_exemptions_engine/applicant_phone_forms_spec.rb
Rename of the parameters to be in line with the model attribute name and permit a delegate.
> Forms refactoring - applicant phone number

- app/services/waste_exemptions_engine/address_finder_service.rb
Fixes https://errbit.aws-int.defra.cloud/apps/5c791b22164f51059600021b/problems/5d665f168b6ebb05500000f6
> Fix error on Airbrake report

- spec/dummy/db/schema.rb
Following: DEFRA/waste-exemptions-back-office#383
> Update schema following RUBY-580

- app/assets/stylesheets/waste_exemptions_engine/application.scss
- app/assets/stylesheets/waste_exemptions_engine/partials/_exemptions.scss
- app/views/waste_exemptions_engine/exemptions_forms/new.html.erb
- config/locales/forms/exemptions_forms/en.yml
- spec/cassettes/w3c_valid_content/exemptions_forms_spec/when-the-registration-is-in-the-correct-state.yml
From: https://eaflood.atlassian.net/browse/RUBY-608
Update exemptions style to make sure screen readers capture the correct information
> Update exemptions style

- spec/cassettes/company_no_valid.yml
- spec/cassettes/postcode_no_matches.yml
- spec/cassettes/postcode_valid.yml
This is a fortnightly maintenance task
> Update VCR cassettes

- app/controllers/concerns/waste_exemptions_engine/cannot_go_back_form.rb
- app/controllers/concerns/waste_exemptions_engine/cannot_submit_form.rb
- app/controllers/concerns/waste_exemptions_engine/unsubmittable_form.rb
- app/controllers/waste_exemptions_engine/edit_cancelled_forms_controller.rb
- app/controllers/waste_exemptions_engine/edit_complete_forms_controller.rb
- app/controllers/waste_exemptions_engine/register_in_northern_ireland_forms_controller.rb
- app/controllers/waste_exemptions_engine/register_in_scotland_forms_controller.rb
- app/controllers/waste_exemptions_engine/register_in_wales_forms_controller.rb
- app/controllers/waste_exemptions_engine/registration_complete_forms_controller.rb
- app/controllers/waste_exemptions_engine/renewal_complete_forms_controller.rb
From: https://github.com/DEFRA/ruby-services-team/issues/55
> Externalise go back and create overrides to concerns

- spec/services/waste_exemptions_engine/edit_completion_service_spec.rb
Closes: https://github.com/DEFRA/ruby-services-team/issues/53
I have been taking a look at this issue and seems like it was already resolved. I did add some test coverage anyway, not sure if is worth merging it in
> Add test coverage for delete of orphaned records

- Gemfile.lock
- waste_exemptions_engine.gemspec
This was previously locked to the latest version (at the time). But we don't really need to lock it, and in fact would like to get the latest updates for Rails 6.
> Update validation gem

- .github/workflows/ci.yml
This was out of sync with the version that we are actually using on the servers.
> Update Ubuntu verson in CI

- app/views/pages/invalid.html.erb
- app/views/pages/os-terms.html.erb
- app/views/pages/version.html.erb
Includes:
- Invalid ID
- Ordnance Survey terms and conditions
- Version
https://eaflood.atlassian.net/browse/RUBY-1653
> Styling: Static pages

- app/views/waste_exemptions_engine/errors/error_401.html.erb
- app/views/waste_exemptions_engine/errors/error_403.html.erb
- app/views/waste_exemptions_engine/errors/error_404.html.erb
- app/views/waste_exemptions_engine/errors/error_422.html.erb
- app/views/waste_exemptions_engine/errors/error_generic.html.erb
- spec/cassettes/w3c_valid_content/errors_spec/-show.yml
https://eaflood.atlassian.net/browse/RUBY-1654
> Styling: Error pages

- config/locales/en.yml
https://eaflood.atlassian.net/browse/RUBY-1653?focusedCommentId=353957
> Update Invalid ID error text

- app/controllers/waste_exemptions_engine/check_contact_phone_forms_controller.rb
- app/forms/waste_exemptions_engine/check_contact_phone_form.rb
- app/models/concerns/waste_exemptions_engine/can_use_new_registration_workflow.rb
- app/models/waste_exemptions_engine/transient_registration.rb
- app/views/waste_exemptions_engine/check_contact_phone_forms/new.html.erb
- config/locales/forms/check_contact_phone_forms/en.yml
- config/routes.rb
- db/migrate/20220330095115_add_temp_reuse_applicant_phone_to_transient_registrations.rb
- spec/cassettes/w3c_valid_content/check_contact_phone_forms_spec/when-the-registration-is-in-the-correct-state.yml
- spec/dummy/db/schema.rb
- spec/factories/forms/check_contact_phone_form.rb
- spec/forms/waste_exemptions_engine/check_contact_phone_form_spec.rb
- spec/models/waste_exemptions_engine/new_registration_workflow_state/check_contact_phone_form_spec.rb
- spec/models/waste_exemptions_engine/new_registration_workflow_state/contact_phone_form_spec.rb
- spec/models/waste_exemptions_engine/new_registration_workflow_state/contact_position_form_spec.rb
- spec/requests/waste_exemptions_engine/check_contact_phone_forms_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1840
> Playback application_phone as contact_phone

- lib/defra_ruby_companies_house.rb
- spec/dummy/config/application.rb
- spec/fixtures/files/companies_house_response.json
- spec/lib/defra_ruby_companies_house_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1872
> Introduce DefraRubyCompaniesHouse to retrieve company details

- app/helpers/waste_exemptions_engine/application_helper.rb
- app/views/waste_exemptions_engine/renewal_complete_forms/new.html.erb
- config/locales/forms/renewal_complete_forms/en.yml
https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-564
> [RUBY-564] WEX Content amend on 'You have renewed' screen - Screen 32

- db/migrate/20220705144056_companies_house_updated_at_added_to_transient_registration.rb
- spec/dummy/db/schema.rb
https://eaflood.atlassian.net/browse/RUBY-1881
Here we are updating the db to include companies_house_updated_at in the transient_registrations
> Added db migration for companies_house_updated_at

- app/views/waste_exemptions_engine/check_registered_name_and_address_forms/inactive_company.html.erb
- config/locales/forms/check_registered_name_and_address_forms/en.yml
https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-1885
Small content change including the company number on the inactive company page
> Inactive company content change

- spec/factories/forms/registration_complete_form.rb
- spec/factories/new_registration.rb
- spec/factories/transient_registration_exemption.rb
https://eaflood.atlassian.net/browse/RUBY-2071
Here we have the fix for the intermittent test failure for expiry_date
> Adding attribute to factory

- .github/workflows/brakeman-analysis.yml
- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- app/models/concerns/waste_exemptions_engine/can_activate_exemption.rb
- app/models/waste_exemptions_engine/registration.rb
- sonar-project.properties
- spec/models/waste_exemptions_engine/registration_spec.rb
- spec/models/waste_exemptions_engine/transient_registration_exemption_spec.rb
- spec/support/simplecov.rb
- waste_exemptions_engine.gemspec
This change sets the expiry date for renewals to three years from original registration expiry date, as opposed to the existing value of three years from the date of the renewal.
https://eaflood.atlassian.net/browse/RUBY-2167
> Modify renewal expiry date logic

- lib/waste_exemptions_engine.rb
Set Errbit environment name for non-production environments
https://eaflood.atlassian.net/browse/RUBY-2255
> Set Errbit environment name for non-production environments

- app/forms/waste_exemptions_engine/edit_exemptions_form.rb
- app/models/waste_exemptions_engine/transient_registration.rb
- app/services/waste_exemptions_engine/exemption_deregistration_service.rb
- app/services/waste_exemptions_engine/registration_edit_confirmation_email_service.rb
- app/views/waste_exemptions_engine/confirm_edit_exemptions_forms/new.html.erb
- app/views/waste_exemptions_engine/deregistration_complete_full_forms/new.html.erb
- app/views/waste_exemptions_engine/deregistration_complete_partial_forms/new.html.erb
- config/locales/forms/deregistration_complete_partial_forms/en.yml
- db/migrate/20230218155859_add_excluded_exemptions_to_transient_registration.rb
- spec/cassettes/w3c_valid_content/deregistration_complete_full_forms_spec/when-the-registration-is-in-the-correct-state.yml
- spec/cassettes/w3c_valid_content/deregistration_complete_partial_forms_spec/when-the-registration-is-in-the-correct-state.yml
- spec/controllers/waste_exemptions_engine/edit_exemptions_declaration_forms_controller_spec.rb
- spec/dummy/db/schema.rb
- spec/models/waste_exemptions_engine/transient_registration_spec.rb
- spec/services/waste_exemptions_engine/exemption_deregistration_service_spec.rb
This fixes issues with deregistration status, confirmation emails, workflows and content.
https://eaflood.atlassian.net/browse/RUBY-2137
https://eaflood.atlassian.net/browse/RUBY-2356
https://eaflood.atlassian.net/browse/RUBY-2136
https://eaflood.atlassian.net/browse/RUBY-2135
> Deregistration fixes

- app/controllers/waste_exemptions_engine/confirm_no_exemption_changes_forms_controller.rb
- app/forms/waste_exemptions_engine/confirm_no_exemption_changes_form.rb
- app/models/concerns/waste_exemptions_engine/can_copy_data_from_registration.rb
- app/models/concerns/waste_exemptions_engine/can_use_renewing_registration_workflow.rb
- app/views/waste_exemptions_engine/confirm_no_exemption_changes_forms/new.html.erb
- app/views/waste_exemptions_engine/deregistration_complete_full_forms/new.html.erb
- app/views/waste_exemptions_engine/deregistration_complete_partial_forms/new.html.erb
- config/locales/forms/confirm_no_exemption_changes_forms/en.yml
- config/locales/forms/deregistration_complete_full_forms/en.yml
- config/locales/forms/deregistration_complete_partial_forms/en.yml
- config/routes.rb
- db/migrate/20230117062339_add_deregistration_email_sent_at_to_registrations.rb
- db/migrate/20230210062223_create_tsm_system_rows_extension.rb
- db/migrate/20230216072536_create_deregistration_email_batch_indexes.rb
- spec/cassettes/w3c_valid_content/deregistration_complete_full_forms_spec/when-the-registration-is-in-the-correct-state.yml
- spec/cassettes/w3c_valid_content/deregistration_complete_partial_forms_spec/when-the-registration-is-in-the-correct-state.yml
- spec/controllers/waste_exemptions_engine/confirm_no_exemption_changes_forms_controller_spec.rb
- spec/dummy/db/schema.rb
- spec/forms/waste_exemptions_engine/confirm_no_exemption_changes_form_spec.rb
- spec/models/waste_exemptions_engine/renewing_registration_workflow_state/confirm_no_exemption_changes_form_spec.rb
- spec/support/factories/forms/confirm_no_exemption_changes_form.rb
This adds a form to allow a user to confirm no de-registrations.
https://eaflood.atlassian.net/browse/RUBY-2244
> Confirm no changes

- app/views/waste_exemptions_engine/deregistration_complete_full_forms/new.html.erb
- app/views/waste_exemptions_engine/deregistration_complete_partial_forms/new.html.erb
https://eaflood.atlassian.net/browse/RUBY-2136
> fix survey link

- config/locales/forms/incorrect_company_forms/en.yml
Incorrect reference to Waste carriers in companies house lookup logic
> Removing reference to Waste carriers

- app/views/waste_exemptions_engine/applicant_name_forms/new.html.erb
- app/views/waste_exemptions_engine/contact_name_forms/new.html.erb
- app/views/waste_exemptions_engine/contact_position_forms/new.html.erb
- app/views/waste_exemptions_engine/contact_postcode_forms/new.html.erb
- app/views/waste_exemptions_engine/operator_name_forms/new.html.erb
- app/views/waste_exemptions_engine/operator_postcode_forms/new.html.erb
- app/views/waste_exemptions_engine/shared/_manual_address.html.erb
- app/views/waste_exemptions_engine/shared/_person_name.html.erb
- app/views/waste_exemptions_engine/site_postcode_forms/new.html.erb
- spec/cassettes/w3c_valid_content/applicant_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
- spec/cassettes/w3c_valid_content/contact_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
- spec/cassettes/w3c_valid_content/contact_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
- spec/cassettes/w3c_valid_content/contact_position_forms_spec/when-the-registration-is-in-the-correct-state.yml
- spec/cassettes/w3c_valid_content/contact_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
- spec/cassettes/w3c_valid_content/main_people_forms_spec/when-the-registration-is-in-the-correct-state.yml
- spec/cassettes/w3c_valid_content/operator_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
- spec/cassettes/w3c_valid_content/operator_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
- spec/cassettes/w3c_valid_content/operator_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
- spec/cassettes/w3c_valid_content/site_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
WEX - accessibility issue - missing autocomplete attributes
https://eaflood.atlassian.net/browse/RUBY-2126
> adding autocomplete

- Gemfile.lock
- config/locales/forms/declaration_forms/en.yml
https://eaflood.atlassian.net/browse/RUBY-2286
> Update declaration text

- app/views/waste_exemptions_engine/renew_exemptions_forms/new.html.erb
https://eaflood.atlassian.net/browse/RUBY-2551
> Show only active registrations on the renewal page

- app/views/waste_exemptions_engine/registration_complete_forms/new.html.erb
- app/views/waste_exemptions_engine/renewal_complete_forms/new.html.erb
- config/locales/forms/registration_complete_forms/en.yml
- spec/cassettes/w3c_valid_content/renewal_complete_forms_spec/GET-renewal_complete_form.yml
This adds a survey link to the registration complete page, and changes the survey link on the renewal complete page to open in a new tab.
https://eaflood.atlassian.net/browse/RUBY-2304
> add registration complete survey link

- config/locales/forms/exemptions_forms/en.yml
https://eaflood.atlassian.net/browse/RUBY-2697
> Update content on choose exemptions page

- app/controllers/waste_exemptions_engine/application_controller.rb
- spec/requests/waste_exemptions_engine/forms_spec.rb
Ensure unhandled exceptions are logged, with registration reference if available.
https://eaflood.atlassian.net/browse/RUBY-2735
> Add unhandled exception logging

- config/locales/pdfs/certificate.en.yml
https://eaflood.atlassian.net/browse/RUBY-2775
> [RUBY-2775] content change

- app/controllers/waste_exemptions_engine/front_office_edit_forms_controller.rb
- app/models/concerns/waste_exemptions_engine/can_use_front_office_edit_registration_workflow.rb
- app/models/waste_exemptions_engine/front_office_edit_registration.rb
- app/services/waste_exemptions_engine/front_office_edit_completion_service.rb
- app/views/waste_exemptions_engine/front_office_edit_forms/new.html.erb
- config/locales/forms/front_office_edit_forms/en.yml
- config/routes.rb
- spec/models/waste_exemptions_engine/front_office_edit_registration_spec.rb
- spec/models/waste_exemptions_engine/front_office_edit_registration_workflow_state/front_office_edit_form_spec.rb
- spec/requests/waste_exemptions_engine/front_office_edit_forms_spec.rb
- spec/services/waste_exemptions_engine/front_office_edit_completion_service_spec.rb
https://eaflood.atlassian.net/browse/RUBY-2785
> [RUBY-2785] ability to edit contact address

- app/models/concerns/waste_exemptions_engine/can_convert_pence_to_pounds.rb
- app/models/waste_exemptions_engine/band.rb
- spec/models/waste_exemptions_engine/band_spec.rb
- spec/models/waste_exemptions_engine/concerns/can_convert_pence_to_pounds_spec.rb
- spec/support/factories/band.rb
Ability to manage prices in pence as pounds
https://eaflood.atlassian.net/browse/RUBY-3113
> [RUBY-3113] Rails concern with ability to manage prices in pence as pounds

- app/forms/waste_exemptions_engine/exemptions_form.rb
- spec/requests/waste_exemptions_engine/exemptions_forms_spec.rb
https://eaflood.atlassian.net/browse/RUBY-3120
> raise an error when no exemptions selected ON CYA change exemptions flow
